@echo off
setlocal EnableExtensions DisableDelayedExpansion
chcp 65001 >nul
title TraceTrackCar TI UART0 RX polling fallback fix

set "PROJECT_ROOT=%~dp0"
set "PATCH_ID=%RANDOM%_%RANDOM%"
set "PATCH_B64=%TEMP%\TI_UART_RX_FIX_%PATCH_ID%.b64"
set "PATCH_PS1=%TEMP%\TI_UART_RX_FIX_%PATCH_ID%.ps1"
set "PATCH_LOG=%TEMP%\TI_UART_RX_FIX_%PATCH_ID%.log"

echo TraceTrackCar TI UART0 RX polling fallback fix
echo Project root: %PROJECT_ROOT%
echo Preparing UTF-8 PowerShell script...

pushd "%PROJECT_ROOT%" >nul 2>&1
if errorlevel 1 (
    echo.
    echo [FAILED] Cannot enter project root.
    pause
    exit /b 1
)

> "%PATCH_B64%" type nul
>>"%PATCH_B64%" echo(77u/JEVycm9yQWN0aW9uUHJlZmVyZW5jZSA9ICdTdG9wJwpbQ29uc29sZV06Ok91dHB1dEVuY29k
>>"%PATCH_B64%" echo(aW5nID0gTmV3LU9iamVjdCBTeXN0ZW0uVGV4dC5VVEY4RW5jb2RpbmcoJGZhbHNlKQokT3V0cHV0
>>"%PATCH_B64%" echo(RW5jb2RpbmcgPSBbQ29uc29sZV06Ok91dHB1dEVuY29kaW5nCgokUHJvamVjdFJvb3QgPSBbSU8u
>>"%PATCH_B64%" echo(UGF0aF06OkdldEZ1bGxQYXRoKChHZXQtTG9jYXRpb24pLlBhdGgpCiRFeHBlY3RlZEhlYWQgPSAn
>>"%PATCH_B64%" echo(MTEyZjYxMzY1OGMxMTNiYTk1OGZjMmM1YjYzYTYyZWE1ZGZlNzRmNScKJFJlbGF0aXZlUGF0aCA9
>>"%PATCH_B64%" echo(ICdVc2VyL0JTUC9ic3BfdWFydC5jJwokVXRmOFN0cmljdCA9IE5ldy1PYmplY3QgU3lzdGVtLlRl
>>"%PATCH_B64%" echo(eHQuVVRGOEVuY29kaW5nKCRmYWxzZSwgJHRydWUpCiRVdGY4Tm9Cb20gPSBOZXctT2JqZWN0IFN5
>>"%PATCH_B64%" echo(c3RlbS5UZXh0LlVURjhFbmNvZGluZygkZmFsc2UpCiRCYWNrdXBSb290ID0gSm9pbi1QYXRoICRl
>>"%PATCH_B64%" echo(bnY6VEVNUCAoCiAgICAnVHJhY2VUcmFja0Nhcl9USV9VQVJUX1JYX0ZJWF8nICsgKEdldC1EYXRl
>>"%PATCH_B64%" echo(IC1Gb3JtYXQgJ3l5eXlNTWRkX0hIbW1zcycpCikKCiRIZWxwZXJCYXNlNjQgPSAnYzNSaGRHbGpJ
>>"%PATCH_B64%" echo(SFp2YVdRZ1ZVRlNWRjlRZFhOb1VuaENlWFJsS0ZWQlVsUmZVRzl5ZEY5MElIQnZjblFzSUhWcGJu
>>"%PATCH_B64%" echo(UTRYM1FnZG1Gc2RXVXBDbnNLSUNBZ0lGVkJVbFJmVW5WdWRHbHRaVjkwSUNweWREc0tJQ0FnSUhW
>>"%PATCH_B64%" echo(cGJuUXhObDkwSUc1bGVIUTdDZ29nSUNBZ2FXWWdLSEJ2Y25RZ1BqMGdWVUZTVkY5UVQxSlVYME5Q
>>"%PATCH_B64%" echo(VlU1VUtTQjdDaUFnSUNBZ0lDQWdjbVYwZFhKdU93b2dJQ0FnZlFvS0lDQWdJSEowSUQwZ0puTmZk
>>"%PATCH_B64%" echo(V0Z5ZEY5eWRGdHdiM0owWFRzS0lDQWdJRzVsZUhRZ1BTQlZRVkpVWDA1bGVIUW9jblF0UG5KNFgy
>>"%PATCH_B64%" echo(aGxZV1FzSUZWQlVsUmZVbGhmUWxWR1gxTkpXa1VwT3dvS0lDQWdJR2xtSUNodVpYaDBJRDA5SUhK
>>"%PATCH_B64%" echo(MExUNXllRjkwWVdsc0tTQjdDaUFnSUNBZ0lDQWdjblF0UG5KNFgyOTJaWEptYkc5M0t5czdDaUFn
>>"%PATCH_B64%" echo(SUNBZ0lDQWdjbVYwZFhKdU93b2dJQ0FnZlFvS0lDQWdJSE5mZFdGeWRGOXllRjl5YVc1blczQnZj
>>"%PATCH_B64%" echo(blJkVzNKMExUNXllRjlvWldGa1hTQTlJSFpoYkhWbE93b2dJQ0FnY25RdFBuSjRYMmhsWVdRZ1BT
>>"%PATCH_B64%" echo(QnVaWGgwT3dwOUNnb3ZLZ29nS2lCU1dPUzRyZWFXcmVTN2plYVlyK1M0dStpbWdlYU9wZWFVdHVp
>>"%PATCH_B64%" echo(M3IrVytoTys4bStXUWp1V1BzT1M3dStXS29lV1FqT2FYdHVpOXJ1aXZvdWVock9TN3RrWkpSay9r
>>"%PATCH_B64%" echo(dlp6a3VMcmxoWnpsdXBYamdJSUtJQ29nNkwrWjVxQzM1WTJ6NUwyLzVwK1E1TGlxVlVGU1ZPZWFo
>>"%PATCH_B64%" echo(RTVXU1VNdjVaQ1I2WWVQNXBxQzVwZTI1cktoNXB5SjZMK2I1WVdsNzd5TTVvNmw1cFMyNUxtZjVM
>>"%PATCH_B64%" echo(aU41THlhNWE2TTVZV281YVN4NXBXSTQ0Q0NDaUFxSU9pd2crZVVxT1dScU9hY24rUzR1akVnYlhQ
>>"%PATCH_B64%" echo(bWw3YnZ2SXptcjQvbXJLSGxqNnJta0t6bnFicmx2WlBsaVkxR1NVWlA3N3lNNUxpTjZMK2I2S0dN
>>"%PATCH_B64%" echo(NUx1NzVMMlY2Wmk3NWFHZTU2Mko1YjZGNDRDQ0NpQXFMd3B6ZEdGMGFXTWdkbTlwWkNCVlFWSlVY
>>"%PATCH_B64%" echo(MFJ5WVdsdVVuaEdhV1p2S0ZWQlVsUmZVRzl5ZEY5MElIQnZjblFwQ25zS0lDQWdJRlZCVWxSZlVt
>>"%PATCH_B64%" echo(Vm5jeUFxYVc1emREc0tJQ0FnSUhWcGJuUXpNbDkwSUhCeWFXMWhjMnM3Q2dvZ0lDQWdhV1lnS0hC
>>"%PATCH_B64%" echo(dmNuUWdQajBnVlVGU1ZGOVFUMUpVWDBOUFZVNVVLU0I3Q2lBZ0lDQWdJQ0FnY21WMGRYSnVPd29n
>>"%PATCH_B64%" echo(SUNBZ2ZRb0tJQ0FnSUhCeWFXMWhjMnNnUFNCQ1UxQmZSVzUwWlhKRGNtbDBhV05oYkNncE93b2dJ
>>"%PATCH_B64%" echo(Q0FnYVc1emRDQTlJSE5mZFdGeWRGOWpabWRiY0c5eWRGMHVhVzV6ZERzS0NpQWdJQ0IzYUdsc1pT
>>"%PATCH_B64%" echo(QW9JVVJNWDFWQlVsUmZUV0ZwYmw5cGMxSllSa2xHVDBWdGNIUjVLR2x1YzNRcEtTQjdDaUFnSUNB
>>"%PATCH_B64%" echo(Z0lDQWdWVUZTVkY5UWRYTm9VbmhDZVhSbEtBb2dJQ0FnSUNBZ0lDQWdJQ0J3YjNKMExBb2dJQ0Fn
>>"%PATCH_B64%" echo(SUNBZ0lDQWdJQ0FvZFdsdWREaGZkQ2xFVEY5VlFWSlVYMDFoYVc1ZmNtVmpaV2wyWlVSaGRHRW9h
>>"%PATCH_B64%" echo(VzV6ZENrS0lDQWdJQ0FnSUNBcE93b2dJQ0FnZlFvS0lDQWdJRUpUVUY5RmVHbDBRM0pwZEdsallX
>>"%PATCH_B64%" echo(d29jSEpwYldGemF5azdDbjBLQ2c9PScKJFRhc2tCYXNlNjQgPSAnZG05cFpDQkNVMUJmVlVGU1ZG
>>"%PATCH_B64%" echo(OVVZWE5yS0ZWQlVsUmZVRzl5ZEY5MElIQnZjblFwQ25zS0lDQWdJR2xtSUNod2IzSjBJRDQ5SUZW
>>"%PATCH_B64%" echo(QlVsUmZVRTlTVkY5RFQxVk9WQ2tnZXdvZ0lDQWdJQ0FnSUhKbGRIVnlianNLSUNBZ0lIMEtDaUFn
>>"%PATCH_B64%" echo(SUNBdktnb2dJQ0FnSUNvZ1ZGam5sTEhuanEvbHZhTG52SlBsaHJMbGpMcmxrb3prdUszbWxxM21q
>>"%PATCH_B64%" echo(cWpvdjV2dnZKc0tJQ0FnSUNBcUlGSlk2Wm1rNUxpdDVwYXQ1YVNXNVlhTjZMMnU2SytpNUxpQTVx
>>"%PATCH_B64%" echo(eWhSa2xHVCsrOGpPbUJ2K1dGamVhT3BlYVV0dVM0cmVhV3JlVzhndVc0dU9hWHR1YVZ0T2Fkb2Vt
>>"%PATCH_B64%" echo(VHZ1aTNyK1drc2VhVmlPT0FnZ29nSUNBZ0lDb3ZDaUFnSUNCVlFWSlVYMFJ5WVdsdVVuaEdhV1p2
>>"%PATCH_B64%" echo(S0hCdmNuUXBPd29nSUNBZ1ZVRlNWRjlMYVdOclZIZ29jRzl5ZENrN0NuMD0nCiRJc3JCYXNlNjQg
>>"%PATCH_B64%" echo(PSAnZG05cFpDQkNVMUJmVlVGU1ZGOVZVMEZTVkY5SlUxSW9WVUZTVkY5UWIzSjBYM1FnY0c5eWRD
>>"%PATCH_B64%" echo(a0tld29nSUNBZ1ZVRlNWRjlTWldkeklDcHBibk4wT3dvZ0lDQWdSRXhmVlVGU1ZGOUpTVVJZSUds
>>"%PATCH_B64%" echo(cFpIZzdDZ29nSUNBZ2FXWWdLSEJ2Y25RZ1BqMGdWVUZTVkY5UVQxSlVYME5QVlU1VUtTQjdDaUFn
>>"%PATCH_B64%" echo(SUNBZ0lDQWdjbVYwZFhKdU93b2dJQ0FnZlFvS0lDQWdJR2x1YzNRZ1BTQnpYM1ZoY25SZlkyWm5X
>>"%PATCH_B64%" echo(M0J2Y25SZExtbHVjM1E3Q2dvZ0lDQWdaRzhnZXdvZ0lDQWdJQ0FnSUdscFpIZ2dQU0JFVEY5VlFW
>>"%PATCH_B64%" echo(SlVYMDFoYVc1ZloyVjBVR1Z1WkdsdVowbHVkR1Z5Y25Wd2RDaHBibk4wS1RzS0NpQWdJQ0FnSUNB
>>"%PATCH_B64%" echo(Z2FXWWdLR2xwWkhnZ1BUMGdSRXhmVlVGU1ZGOU5RVWxPWDBsSlJGaGZVbGdwSUhzS0lDQWdJQ0Fn
>>"%PATCH_B64%" echo(SUNBZ0lDQWdWVUZTVkY5RWNtRnBibEo0Um1sbWJ5aHdiM0owS1RzS0lDQWdJQ0FnSUNCOUlHVnNj
>>"%PATCH_B64%" echo(MlVnYVdZZ0tHbHBaSGdnUFQwZ1JFeGZWVUZTVkY5TlFVbE9YMGxKUkZoZlZGZ3BJSHNLSUNBZ0lD
>>"%PATCH_B64%" echo(QWdJQ0FnSUNBZ1ZVRlNWRjlMYVdOclZIZ29jRzl5ZENrN0NpQWdJQ0FnSUNBZ2ZTQmxiSE5sSUds
>>"%PATCH_B64%" echo(bUlDZ29hV2xrZUNBOVBTQkVURjlWUVZKVVgwMUJTVTVmU1VsRVdGOVBWa1ZTVWxWT1gwVlNVazlT
>>"%PATCH_B64%" echo(S1NCOGZBb2dJQ0FnSUNBZ0lDQWdJQ0FnSUNBZ0lDQWdLR2xwWkhnZ1BUMGdSRXhmVlVGU1ZGOU5R
>>"%PATCH_B64%" echo(VWxPWDBsSlJGaGZRbEpGUVV0ZlJWSlNUMUlwSUh4OENpQWdJQ0FnSUNBZ0lDQWdJQ0FnSUNBZ0lD
>>"%PATCH_B64%" echo(QW9hV2xrZUNBOVBTQkVURjlWUVZKVVgwMUJTVTVmU1VsRVdGOVFRVkpKVkZsZlJWSlNUMUlwSUh4
>>"%PATCH_B64%" echo(OENpQWdJQ0FnSUNBZ0lDQWdJQ0FnSUNBZ0lDQW9hV2xrZUNBOVBTQkVURjlWUVZKVVgwMUJTVTVm
>>"%PATCH_B64%" echo(U1VsRVdGOUdVa0ZOU1U1SFgwVlNVazlTS1NCOGZBb2dJQ0FnSUNBZ0lDQWdJQ0FnSUNBZ0lDQWdL
>>"%PATCH_B64%" echo(R2xwWkhnZ1BUMGdSRXhmVlVGU1ZGOU5RVWxPWDBsSlJGaGZVbGhmVkVsTlJVOVZWRjlGVWxKUFVp
>>"%PATCH_B64%" echo(a2dmSHdLSUNBZ0lDQWdJQ0FnSUNBZ0lDQWdJQ0FnSUNocGFXUjRJRDA5SUVSTVgxVkJVbFJmVFVG
>>"%PATCH_B64%" echo(SlRsOUpTVVJZWDA1UFNWTkZYMFZTVWs5U0tTa2dld29nSUNBZ0lDQWdJQ0FnSUNBdktnb2dJQ0Fn
>>"%PATCH_B64%" echo(SUNBZ0lDQWdJQ0FnS2lEcGxKbm9yNi9rdUszbWxxM2xqNUhubEovbWw3Ymt1NDNsc0ozb3I1WGxq
>>"%PATCH_B64%" echo(NWJvdGJCR1NVWlA1TGl0NTVxRTVweUo1cFdJNWEyWDZJcUM3N3lNQ2lBZ0lDQWdJQ0FnSUNBZ0lD
>>"%PATCH_B64%" echo(QXFJT1dRanVlN3JlV1ByK21BbXVpL2gzSjRYMjkyWlhKbWJHOTM1WktNNUxpVDZaZW82WlNaNksr
>>"%PATCH_B64%" echo(djZLNmg1cFd3NTd1bjU3dXQ2SytLNXBhdDQ0Q0NDaUFnSUNBZ0lDQWdJQ0FnSUNBcUx3b2dJQ0Fn
>>"%PATCH_B64%" echo(SUNBZ0lDQWdJQ0JWUVZKVVgwUnlZV2x1VW5oR2FXWnZLSEJ2Y25RcE93b2dJQ0FnSUNBZ0lIMEtJ
>>"%PATCH_B64%" echo(Q0FnSUgwZ2QyaHBiR1VnS0dscFpIZ2dJVDBnUkV4ZlZVRlNWRjlOUVVsT1gwbEpSRmhmVGs5ZlNV
>>"%PATCH_B64%" echo(NVVSVkpTVlZCVUtUc0tmUT09JwoKZnVuY3Rpb24gR2V0LVByb2plY3RGaWxlUGF0aCB7CiAgICBw
>>"%PATCH_B64%" echo(YXJhbShbc3RyaW5nXSRQcm9qZWN0UmVsYXRpdmVQYXRoKQoKICAgIHJldHVybiBKb2luLVBhdGgg
>>"%PATCH_B64%" echo(JFByb2plY3RSb290ICgkUHJvamVjdFJlbGF0aXZlUGF0aCAtcmVwbGFjZSAnLycsICdcJykKfQoK
>>"%PATCH_B64%" echo(ZnVuY3Rpb24gUmVhZC1Qcm9qZWN0VXRmOCB7CiAgICBwYXJhbShbc3RyaW5nXSRQcm9qZWN0UmVs
>>"%PATCH_B64%" echo(YXRpdmVQYXRoKQoKICAgICRQYXRoID0gR2V0LVByb2plY3RGaWxlUGF0aCAkUHJvamVjdFJlbGF0
>>"%PATCH_B64%" echo(aXZlUGF0aAogICAgaWYgKC1ub3QgKFRlc3QtUGF0aCAtTGl0ZXJhbFBhdGggJFBhdGggLVBhdGhU
>>"%PATCH_B64%" echo(eXBlIExlYWYpKSB7CiAgICAgICAgdGhyb3cgKCfnvLrlsJHlt6XnqIvmlofku7bvvJonICsgJFBy
>>"%PATCH_B64%" echo(b2plY3RSZWxhdGl2ZVBhdGgpCiAgICB9CgogICAgcmV0dXJuIFtJTy5GaWxlXTo6UmVhZEFsbFRl
>>"%PATCH_B64%" echo(eHQoJFBhdGgsICRVdGY4U3RyaWN0KQp9CgpmdW5jdGlvbiBEZWNvZGUtVXRmOEJhc2U2NCB7CiAg
>>"%PATCH_B64%" echo(ICBwYXJhbShbc3RyaW5nXSRFbmNvZGVkVGV4dCkKCiAgICByZXR1cm4gW1RleHQuRW5jb2Rpbmdd
>>"%PATCH_B64%" echo(OjpVVEY4LkdldFN0cmluZygKICAgICAgICBbQ29udmVydF06OkZyb21CYXNlNjRTdHJpbmcoJEVu
>>"%PATCH_B64%" echo(Y29kZWRUZXh0KQogICAgKQp9CgpmdW5jdGlvbiBSZXBsYWNlLUNGdW5jdGlvbiB7CiAgICBwYXJh
>>"%PATCH_B64%" echo(bSgKICAgICAgICBbc3RyaW5nXSRUZXh0LAogICAgICAgIFtzdHJpbmddJFNpZ25hdHVyZSwKICAg
>>"%PATCH_B64%" echo(ICAgICBbc3RyaW5nXSRSZXBsYWNlbWVudAogICAgKQoKICAgICRTdGFydEluZGV4ID0gJFRleHQu
>>"%PATCH_B64%" echo(SW5kZXhPZigkU2lnbmF0dXJlKQogICAgaWYgKCRTdGFydEluZGV4IC1sdCAwKSB7CiAgICAgICAg
>>"%PATCH_B64%" echo(dGhyb3cgKCfmnKrmib7liLDlh73mlbDvvJonICsgJFNpZ25hdHVyZSkKICAgIH0KCiAgICAkQnJh
>>"%PATCH_B64%" echo(Y2VTdGFydCA9ICRUZXh0LkluZGV4T2YoJ3snLCAkU3RhcnRJbmRleCkKICAgIGlmICgkQnJhY2VT
>>"%PATCH_B64%" echo(dGFydCAtbHQgMCkgewogICAgICAgIHRocm93ICgn5Ye95pWw57y65bCR5bem6Iqx5ous5Y+377ya
>>"%PATCH_B64%" echo(JyArICRTaWduYXR1cmUpCiAgICB9CgogICAgJERlcHRoID0gMAogICAgJEluU3RyaW5nID0gJGZh
>>"%PATCH_B64%" echo(bHNlCiAgICAkSW5DaGFyID0gJGZhbHNlCiAgICAkSW5MaW5lQ29tbWVudCA9ICRmYWxzZQogICAg
>>"%PATCH_B64%" echo(JEluQmxvY2tDb21tZW50ID0gJGZhbHNlCiAgICAkRXNjYXBlZCA9ICRmYWxzZQogICAgJEVuZElu
>>"%PATCH_B64%" echo(ZGV4ID0gLTEKCiAgICBmb3IgKCRJbmRleCA9ICRCcmFjZVN0YXJ0OyAkSW5kZXggLWx0ICRUZXh0
>>"%PATCH_B64%" echo(Lkxlbmd0aDsgJEluZGV4KyspIHsKICAgICAgICAkQ3VycmVudCA9ICRUZXh0WyRJbmRleF0KICAg
>>"%PATCH_B64%" echo(ICAgICAkTmV4dCA9IGlmICgoJEluZGV4ICsgMSkgLWx0ICRUZXh0Lkxlbmd0aCkgewogICAgICAg
>>"%PATCH_B64%" echo(ICAgICAkVGV4dFskSW5kZXggKyAxXQogICAgICAgIH0gZWxzZSB7CiAgICAgICAgICAgIFtjaGFy
>>"%PATCH_B64%" echo(XTAKICAgICAgICB9CgogICAgICAgIGlmICgkSW5MaW5lQ29tbWVudCkgewogICAgICAgICAgICBp
>>"%PATCH_B64%" echo(ZiAoJEN1cnJlbnQgLWVxICJgbiIpIHsKICAgICAgICAgICAgICAgICRJbkxpbmVDb21tZW50ID0g
>>"%PATCH_B64%" echo(JGZhbHNlCiAgICAgICAgICAgIH0KICAgICAgICAgICAgY29udGludWUKICAgICAgICB9CgogICAg
>>"%PATCH_B64%" echo(ICAgIGlmICgkSW5CbG9ja0NvbW1lbnQpIHsKICAgICAgICAgICAgaWYgKCgkQ3VycmVudCAtZXEg
>>"%PATCH_B64%" echo(JyonKSAtYW5kICgkTmV4dCAtZXEgJy8nKSkgewogICAgICAgICAgICAgICAgJEluQmxvY2tDb21t
>>"%PATCH_B64%" echo(ZW50ID0gJGZhbHNlCiAgICAgICAgICAgICAgICAkSW5kZXgrKwogICAgICAgICAgICB9CiAgICAg
>>"%PATCH_B64%" echo(ICAgICAgIGNvbnRpbnVlCiAgICAgICAgfQoKICAgICAgICBpZiAoJEluU3RyaW5nKSB7CiAgICAg
>>"%PATCH_B64%" echo(ICAgICAgIGlmICgkRXNjYXBlZCkgewogICAgICAgICAgICAgICAgJEVzY2FwZWQgPSAkZmFsc2UK
>>"%PATCH_B64%" echo(ICAgICAgICAgICAgfSBlbHNlaWYgKCRDdXJyZW50IC1lcSAnXCcpIHsKICAgICAgICAgICAgICAg
>>"%PATCH_B64%" echo(ICRFc2NhcGVkID0gJHRydWUKICAgICAgICAgICAgfSBlbHNlaWYgKCRDdXJyZW50IC1lcSAnIicp
>>"%PATCH_B64%" echo(IHsKICAgICAgICAgICAgICAgICRJblN0cmluZyA9ICRmYWxzZQogICAgICAgICAgICB9CiAgICAg
>>"%PATCH_B64%" echo(ICAgICAgIGNvbnRpbnVlCiAgICAgICAgfQoKICAgICAgICBpZiAoJEluQ2hhcikgewogICAgICAg
>>"%PATCH_B64%" echo(ICAgICBpZiAoJEVzY2FwZWQpIHsKICAgICAgICAgICAgICAgICRFc2NhcGVkID0gJGZhbHNlCiAg
>>"%PATCH_B64%" echo(ICAgICAgICAgIH0gZWxzZWlmICgkQ3VycmVudCAtZXEgJ1wnKSB7CiAgICAgICAgICAgICAgICAk
>>"%PATCH_B64%" echo(RXNjYXBlZCA9ICR0cnVlCiAgICAgICAgICAgIH0gZWxzZWlmICgkQ3VycmVudCAtZXEgIiciKSB7
>>"%PATCH_B64%" echo(CiAgICAgICAgICAgICAgICAkSW5DaGFyID0gJGZhbHNlCiAgICAgICAgICAgIH0KICAgICAgICAg
>>"%PATCH_B64%" echo(ICAgY29udGludWUKICAgICAgICB9CgogICAgICAgIGlmICgoJEN1cnJlbnQgLWVxICcvJykgLWFu
>>"%PATCH_B64%" echo(ZCAoJE5leHQgLWVxICcvJykpIHsKICAgICAgICAgICAgJEluTGluZUNvbW1lbnQgPSAkdHJ1ZQog
>>"%PATCH_B64%" echo(ICAgICAgICAgICAkSW5kZXgrKwogICAgICAgICAgICBjb250aW51ZQogICAgICAgIH0KCiAgICAg
>>"%PATCH_B64%" echo(ICAgaWYgKCgkQ3VycmVudCAtZXEgJy8nKSAtYW5kICgkTmV4dCAtZXEgJyonKSkgewogICAgICAg
>>"%PATCH_B64%" echo(ICAgICAkSW5CbG9ja0NvbW1lbnQgPSAkdHJ1ZQogICAgICAgICAgICAkSW5kZXgrKwogICAgICAg
>>"%PATCH_B64%" echo(ICAgICBjb250aW51ZQogICAgICAgIH0KCiAgICAgICAgaWYgKCRDdXJyZW50IC1lcSAnIicpIHsK
>>"%PATCH_B64%" echo(ICAgICAgICAgICAgJEluU3RyaW5nID0gJHRydWUKICAgICAgICAgICAgY29udGludWUKICAgICAg
>>"%PATCH_B64%" echo(ICB9CgogICAgICAgIGlmICgkQ3VycmVudCAtZXEgIiciKSB7CiAgICAgICAgICAgICRJbkNoYXIg
>>"%PATCH_B64%" echo(PSAkdHJ1ZQogICAgICAgICAgICBjb250aW51ZQogICAgICAgIH0KCiAgICAgICAgaWYgKCRDdXJy
>>"%PATCH_B64%" echo(ZW50IC1lcSAneycpIHsKICAgICAgICAgICAgJERlcHRoKysKICAgICAgICB9IGVsc2VpZiAoJEN1
>>"%PATCH_B64%" echo(cnJlbnQgLWVxICd9JykgewogICAgICAgICAgICAkRGVwdGgtLQoKICAgICAgICAgICAgaWYgKCRE
>>"%PATCH_B64%" echo(ZXB0aCAtZXEgMCkgewogICAgICAgICAgICAgICAgJEVuZEluZGV4ID0gJEluZGV4ICsgMQogICAg
>>"%PATCH_B64%" echo(ICAgICAgICAgICAgYnJlYWsKICAgICAgICAgICAgfQogICAgICAgIH0KICAgIH0KCiAgICBpZiAo
>>"%PATCH_B64%" echo(JEVuZEluZGV4IC1sdCAwKSB7CiAgICAgICAgdGhyb3cgKCfml6Dms5Xnoa7lrprlh73mlbDnu5Pm
>>"%PATCH_B64%" echo(nZ/kvY3nva7vvJonICsgJFNpZ25hdHVyZSkKICAgIH0KCiAgICByZXR1cm4gKAogICAgICAgICRU
>>"%PATCH_B64%" echo(ZXh0LlN1YnN0cmluZygwLCAkU3RhcnRJbmRleCkgKwogICAgICAgICRSZXBsYWNlbWVudC5Ucmlt
>>"%PATCH_B64%" echo(RW5kKCkgKwogICAgICAgICRUZXh0LlN1YnN0cmluZygkRW5kSW5kZXgpCiAgICApCn0KCmZ1bmN0
>>"%PATCH_B64%" echo(aW9uIFdyaXRlLVByb2plY3RVdGY4UHJlc2VydmVFb2wgewogICAgcGFyYW0oCiAgICAgICAgW3N0
>>"%PATCH_B64%" echo(cmluZ10kUHJvamVjdFJlbGF0aXZlUGF0aCwKICAgICAgICBbc3RyaW5nXSRPcmlnaW5hbFRleHQs
>>"%PATCH_B64%" echo(CiAgICAgICAgW3N0cmluZ10kVXBkYXRlZFRleHQKICAgICkKCiAgICAkUGF0aCA9IEdldC1Qcm9q
>>"%PATCH_B64%" echo(ZWN0RmlsZVBhdGggJFByb2plY3RSZWxhdGl2ZVBhdGgKICAgICROb3JtYWxpemVkID0gKCgkVXBk
>>"%PATCH_B64%" echo(YXRlZFRleHQgLXJlcGxhY2UgImByYG4iLCAiYG4iKSAtcmVwbGFjZSAiYHIiLCAiYG4iKQoKICAg
>>"%PATCH_B64%" echo(IGlmICgkT3JpZ2luYWxUZXh0LkNvbnRhaW5zKCJgcmBuIikpIHsKICAgICAgICAkTm9ybWFsaXpl
>>"%PATCH_B64%" echo(ZCA9ICROb3JtYWxpemVkIC1yZXBsYWNlICJgbiIsICJgcmBuIgogICAgfQoKICAgIFtJTy5GaWxl
>>"%PATCH_B64%" echo(XTo6V3JpdGVBbGxUZXh0KCRQYXRoLCAkTm9ybWFsaXplZCwgJFV0ZjhOb0JvbSkKfQoKaWYgKEdl
>>"%PATCH_B64%" echo(dC1Db21tYW5kIGdpdCAtRXJyb3JBY3Rpb24gU2lsZW50bHlDb250aW51ZSkgewogICAgJEN1cnJl
>>"%PATCH_B64%" echo(bnRIZWFkID0gKCYgZ2l0IHJldi1wYXJzZSBIRUFEIDI+JG51bGwpCgogICAgaWYgKCRMQVNURVhJ
>>"%PATCH_B64%" echo(VENPREUgLWVxIDApIHsKICAgICAgICBXcml0ZS1Ib3N0ICgn5b2T5YmNR2l0IEhFQUTvvJonICsg
>>"%PATCH_B64%" echo(JEN1cnJlbnRIZWFkKQoKICAgICAgICBpZiAoJEN1cnJlbnRIZWFkIC1uZSAkRXhwZWN0ZWRIZWFk
>>"%PATCH_B64%" echo(KSB7CiAgICAgICAgICAgIFdyaXRlLUhvc3QgKAogICAgICAgICAgICAgICAgJ+aPkOekuu+8muW9
>>"%PATCH_B64%" echo(k+WJjUhFQUTkuI3mmK/ohJrmnKzmoLjlr7nniYjmnKwgJyArCiAgICAgICAgICAgICAgICAkRXhw
>>"%PATCH_B64%" echo(ZWN0ZWRIZWFkICsKICAgICAgICAgICAgICAgICfvvIzku43kvJrmjInlh73mlbDnu5PmnoTkv67m
>>"%PATCH_B64%" echo(lLnjgIInCiAgICAgICAgICAgICkKICAgICAgICB9CiAgICB9Cn0KCiRQYXRoID0gR2V0LVByb2pl
>>"%PATCH_B64%" echo(Y3RGaWxlUGF0aCAkUmVsYXRpdmVQYXRoCiRPcmlnaW5hbFRleHQgPSBSZWFkLVByb2plY3RVdGY4
>>"%PATCH_B64%" echo(ICRSZWxhdGl2ZVBhdGgKCmZvcmVhY2ggKCRSZXF1aXJlZFRva2VuIGluIEAoCiAgICAnc3RhdGlj
>>"%PATCH_B64%" echo(IHZvaWQgVUFSVF9LaWNrVHgoVUFSVF9Qb3J0X3QgcG9ydCknLAogICAgJ3ZvaWQgQlNQX1VBUlRf
>>"%PATCH_B64%" echo(VGFzayhVQVJUX1BvcnRfdCBwb3J0KScsCiAgICAndm9pZCBCU1BfVUFSVF9VU0FSVF9JU1IoVUFS
>>"%PATCH_B64%" echo(VF9Qb3J0X3QgcG9ydCknLAogICAgJ0RMX1VBUlRfTWFpbl9pc1JYRklGT0VtcHR5JywKICAgICdC
>>"%PATCH_B64%" echo(U1BfVUFSVF9HZXRDaGFyJwopKSB7CiAgICBpZiAoLW5vdCAkT3JpZ2luYWxUZXh0LkNvbnRhaW5z
>>"%PATCH_B64%" echo(KCRSZXF1aXJlZFRva2VuKSkgewogICAgICAgIHRocm93ICgnYnNwX3VhcnQuY+e8uuWwkemihOac
>>"%PATCH_B64%" echo(n+agh+ivhu+8micgKyAkUmVxdWlyZWRUb2tlbikKICAgIH0KfQoKaWYgKCRPcmlnaW5hbFRleHQu
>>"%PATCH_B64%" echo(Q29udGFpbnMoJ3N0YXRpYyB2b2lkIFVBUlRfRHJhaW5SeEZpZm8oVUFSVF9Qb3J0X3QgcG9ydCkn
>>"%PATCH_B64%" echo(KSkgewogICAgV3JpdGUtSG9zdCAnVUFSVCBSWOi9ruivouWFnOW6leW3sue7j+WtmOWcqO+8jOS4
>>"%PATCH_B64%" echo(jemHjeWkjeS/ruaUueOAgicKICAgIGV4aXQgMAp9CgokS2lja0luZGV4ID0gJE9yaWdpbmFsVGV4
>>"%PATCH_B64%" echo(dC5JbmRleE9mKAogICAgJ3N0YXRpYyB2b2lkIFVBUlRfS2lja1R4KFVBUlRfUG9ydF90IHBvcnQp
>>"%PATCH_B64%" echo(JwopCmlmICgkS2lja0luZGV4IC1sdCAwKSB7CiAgICB0aHJvdyAn5peg5rOV5a6a5L2NVUFSVF9L
>>"%PATCH_B64%" echo(aWNrVHjjgIInCn0KCiRVcGRhdGVkVGV4dCA9ICgKICAgICRPcmlnaW5hbFRleHQuU3Vic3RyaW5n
>>"%PATCH_B64%" echo(KDAsICRLaWNrSW5kZXgpICsKICAgIChEZWNvZGUtVXRmOEJhc2U2NCAkSGVscGVyQmFzZTY0KSAr
>>"%PATCH_B64%" echo(CiAgICAkT3JpZ2luYWxUZXh0LlN1YnN0cmluZygkS2lja0luZGV4KQopCgokVXBkYXRlZFRleHQg
>>"%PATCH_B64%" echo(PSBSZXBsYWNlLUNGdW5jdGlvbiBgCiAgICAkVXBkYXRlZFRleHQgYAogICAgJ3ZvaWQgQlNQX1VB
>>"%PATCH_B64%" echo(UlRfVGFzayhVQVJUX1BvcnRfdCBwb3J0KScgYAogICAgKERlY29kZS1VdGY4QmFzZTY0ICRUYXNr
>>"%PATCH_B64%" echo(QmFzZTY0KQoKJFVwZGF0ZWRUZXh0ID0gUmVwbGFjZS1DRnVuY3Rpb24gYAogICAgJFVwZGF0ZWRU
>>"%PATCH_B64%" echo(ZXh0IGAKICAgICd2b2lkIEJTUF9VQVJUX1VTQVJUX0lTUihVQVJUX1BvcnRfdCBwb3J0KScgYAog
>>"%PATCH_B64%" echo(ICAgKERlY29kZS1VdGY4QmFzZTY0ICRJc3JCYXNlNjQpCgpmb3JlYWNoICgkUmVxdWlyZWRUb2tl
>>"%PATCH_B64%" echo(biBpbiBAKAogICAgJ3N0YXRpYyB2b2lkIFVBUlRfUHVzaFJ4Qnl0ZShVQVJUX1BvcnRfdCBwb3J0
>>"%PATCH_B64%" echo(LCB1aW50OF90IHZhbHVlKScsCiAgICAnc3RhdGljIHZvaWQgVUFSVF9EcmFpblJ4RmlmbyhVQVJU
>>"%PATCH_B64%" echo(X1BvcnRfdCBwb3J0KScsCiAgICAnVUFSVF9EcmFpblJ4Rmlmbyhwb3J0KTsnLAogICAgJ0RMX1VB
>>"%PATCH_B64%" echo(UlRfTUFJTl9JSURYX1JYX1RJTUVPVVRfRVJST1InLAogICAgJ1VBUlRfS2lja1R4KHBvcnQpOycK
>>"%PATCH_B64%" echo(KSkgewogICAgaWYgKC1ub3QgJFVwZGF0ZWRUZXh0LkNvbnRhaW5zKCRSZXF1aXJlZFRva2VuKSkg
>>"%PATCH_B64%" echo(ewogICAgICAgIHRocm93ICgn5L+u5pS557uT5p6c57y65bCR77yaJyArICRSZXF1aXJlZFRva2Vu
>>"%PATCH_B64%" echo(KQogICAgfQp9CgpOZXctSXRlbSAtSXRlbVR5cGUgRGlyZWN0b3J5IC1Gb3JjZSAtUGF0aCAkQmFj
>>"%PATCH_B64%" echo(a3VwUm9vdCB8IE91dC1OdWxsCiRCYWNrdXBQYXRoID0gSm9pbi1QYXRoICRCYWNrdXBSb290ICgk
>>"%PATCH_B64%" echo(UmVsYXRpdmVQYXRoIC1yZXBsYWNlICcvJywgJ1wnKQpOZXctSXRlbSAtSXRlbVR5cGUgRGlyZWN0
>>"%PATCH_B64%" echo(b3J5IC1Gb3JjZSBgCiAgICAtUGF0aCAoU3BsaXQtUGF0aCAtUGFyZW50ICRCYWNrdXBQYXRoKSB8
>>"%PATCH_B64%" echo(IE91dC1OdWxsCkNvcHktSXRlbSAtTGl0ZXJhbFBhdGggJFBhdGggLURlc3RpbmF0aW9uICRCYWNr
>>"%PATCH_B64%" echo(dXBQYXRoIC1Gb3JjZQpXcml0ZS1Ib3N0ICgn5aSH5Lu955uu5b2V77yaJyArICRCYWNrdXBSb290
>>"%PATCH_B64%" echo(KQoKdHJ5IHsKICAgIFdyaXRlLVByb2plY3RVdGY4UHJlc2VydmVFb2wgYAogICAgICAgICRSZWxh
>>"%PATCH_B64%" echo(dGl2ZVBhdGggYAogICAgICAgICRPcmlnaW5hbFRleHQgYAogICAgICAgICRVcGRhdGVkVGV4dAoK
>>"%PATCH_B64%" echo(ICAgICRGaW5hbFRleHQgPSBSZWFkLVByb2plY3RVdGY4ICRSZWxhdGl2ZVBhdGgKCiAgICBmb3Jl
>>"%PATCH_B64%" echo(YWNoICgkUmVxdWlyZWRUb2tlbiBpbiBAKAogICAgICAgICdzdGF0aWMgdm9pZCBVQVJUX0RyYWlu
>>"%PATCH_B64%" echo(UnhGaWZvKFVBUlRfUG9ydF90IHBvcnQpJywKICAgICAgICAndm9pZCBCU1BfVUFSVF9UYXNrKFVB
>>"%PATCH_B64%" echo(UlRfUG9ydF90IHBvcnQpJywKICAgICAgICAndm9pZCBCU1BfVUFSVF9VU0FSVF9JU1IoVUFSVF9Q
>>"%PATCH_B64%" echo(b3J0X3QgcG9ydCknCiAgICApKSB7CiAgICAgICAgaWYgKC1ub3QgJEZpbmFsVGV4dC5Db250YWlu
>>"%PATCH_B64%" echo(cygkUmVxdWlyZWRUb2tlbikpIHsKICAgICAgICAgICAgdGhyb3cgKCflhpnlhaXlkI7moKHpqozl
>>"%PATCH_B64%" echo(pLHotKXvvJonICsgJFJlcXVpcmVkVG9rZW4pCiAgICAgICAgfQogICAgfQoKICAgIGlmIChHZXQt
>>"%PATCH_B64%" echo(Q29tbWFuZCBnaXQgLUVycm9yQWN0aW9uIFNpbGVudGx5Q29udGludWUpIHsKICAgICAgICBXcml0
>>"%PATCH_B64%" echo(ZS1Ib3N0ICcnCiAgICAgICAgV3JpdGUtSG9zdCAnR2l05beu5byC5qOA5p+l77yaJwogICAgICAg
>>"%PATCH_B64%" echo(ICYgZ2l0IGRpZmYgLS1jaGVjayAtLSAkUmVsYXRpdmVQYXRoCgogICAgICAgIGlmICgkTEFTVEVY
>>"%PATCH_B64%" echo(SVRDT0RFIC1uZSAwKSB7CiAgICAgICAgICAgIHRocm93ICdic3BfdWFydC5j55qEZ2l0IGRpZmYg
>>"%PATCH_B64%" echo(LS1jaGVja+WPkeeOsOagvOW8j+mXrumimOOAgicKICAgICAgICB9CiAgICB9CgogICAgV3JpdGUt
>>"%PATCH_B64%" echo(SG9zdCAnJwogICAgV3JpdGUtSG9zdCAn5bey5a6M5oiQVUFSVCBSWOS/ruWkje+8micKICAgIFdy
>>"%PATCH_B64%" echo(aXRlLUhvc3QgJyAgUljkuK3mlq3mjqXmlLbkv53nlZknCiAgICBXcml0ZS1Ib3N0ICcgIDEgbXPl
>>"%PATCH_B64%" echo(kI7lj7Dku7vliqHlop7liqDnoazku7ZGSUZP6L2u6K+i5YWc5bqVJwogICAgV3JpdGUtSG9zdCAn
>>"%PATCH_B64%" echo(ICBSWOmUmeivr+S4reaWreWPkeeUn+aXtuS5n+S8muWwneivleaQrOi/kEZJRk8nCiAgICBXcml0
>>"%PATCH_B64%" echo(ZS1Ib3N0ICcgIOacquS/ruaUueS7u+WKoeihqOOAgVN5c0NvbmZpZ+aIluWFtuS7luaooeWdlycK
>>"%PATCH_B64%" echo(ICAgIFdyaXRlLUhvc3QgJycKICAgIFdyaXRlLUhvc3QgJ+ivt1JlYnVpbGQgYWxsIHRhcmdldCBm
>>"%PATCH_B64%" echo(aWxlc+W5tumHjeaWsOeDp+W9leOAgicKfSBjYXRjaCB7CiAgICBXcml0ZS1Ib3N0ICgn5Y+R55Sf
>>"%PATCH_B64%" echo(6ZSZ6K+v77yM5q2j5Zyo5oGi5aSN5aSH5Lu977yaJyArICRfLkV4Y2VwdGlvbi5NZXNzYWdlKQog
>>"%PATCH_B64%" echo(ICAgQ29weS1JdGVtIC1MaXRlcmFsUGF0aCAkQmFja3VwUGF0aCAtRGVzdGluYXRpb24gJFBhdGgg
>>"%PATCH_B64%" echo(LUZvcmNlCiAgICB0aHJvdwp9Cg==

powershell.exe -NoProfile -ExecutionPolicy Bypass -Command ^
  "$b=[IO.File]::ReadAllText($env:PATCH_B64); $b=[Text.RegularExpressions.Regex]::Replace($b,'\s',''); [IO.File]::WriteAllBytes($env:PATCH_PS1,[Convert]::FromBase64String($b))"

if errorlevel 1 (
    echo.
    echo [FAILED] Cannot decode PowerShell script.
    echo Base64 file: %PATCH_B64%
    popd
    pause
    exit /b 1
)

powershell.exe -NoProfile -ExecutionPolicy Bypass -File "%PATCH_PS1%" >"%PATCH_LOG%" 2>&1
set "RC=%ERRORLEVEL%"
type "%PATCH_LOG%"

if "%RC%"=="0" (
    del /q "%PATCH_B64%" "%PATCH_PS1%" "%PATCH_LOG%" >nul 2>nul
    echo.
    echo [OK] TI UART0 RX polling fallback fix completed successfully.
    popd
    pause
    exit /b 0
)

echo.
echo [FAILED] Error code: %RC%
echo Log: %PATCH_LOG%
echo Base64 file: %PATCH_B64%
echo PowerShell file: %PATCH_PS1%
echo bsp_uart.c was restored from backup when writing had started.
popd
pause
exit /b %RC%
