@echo off
setlocal EnableExtensions DisableDelayedExpansion
chcp 65001 >nul
title TraceTrackCar TI chassis stack and UART fix v3

set "PROJECT_ROOT=%~dp0"
set "PATCH_ID=%RANDOM%_%RANDOM%"
set "PATCH_B64=%TEMP%\TI_CHASSIS_FIX_V3_%PATCH_ID%.b64"
set "PATCH_PS1=%TEMP%\TI_CHASSIS_FIX_V3_%PATCH_ID%.ps1"
set "PATCH_LOG=%TEMP%\TI_CHASSIS_FIX_V3_%PATCH_ID%.log"

echo TraceTrackCar TI chassis stack and UART fix v3
echo Project root: %PROJECT_ROOT%
echo Preparing UTF-8 PowerShell script...

pushd "%PROJECT_ROOT%" >nul 2>&1
if errorlevel 1 (
    echo.
    echo [FAILED] Cannot enter project root.
    pause
    exit /b 1
)

> "%PATCH_B64%" type nul
>>"%PATCH_B64%" echo(77u/JEVycm9yQWN0aW9uUHJlZmVyZW5jZSA9ICdTdG9wJwpbQ29uc29sZV06Ok91dHB1dEVuY29k
>>"%PATCH_B64%" echo(aW5nID0gTmV3LU9iamVjdCBTeXN0ZW0uVGV4dC5VVEY4RW5jb2RpbmcoJGZhbHNlKQokT3V0cHV0
>>"%PATCH_B64%" echo(RW5jb2RpbmcgPSBbQ29uc29sZV06Ok91dHB1dEVuY29kaW5nCgokUHJvamVjdFJvb3QgPSBbSU8u
>>"%PATCH_B64%" echo(UGF0aF06OkdldEZ1bGxQYXRoKChHZXQtTG9jYXRpb24pLlBhdGgpCiRFeHBlY3RlZEhlYWQgPSAn
>>"%PATCH_B64%" echo(MTEyZjYxMzY1OGMxMTNiYTk1OGZjMmM1YjYzYTYyZWE1ZGZlNzRmNScKJFV0ZjhTdHJpY3QgPSBO
>>"%PATCH_B64%" echo(ZXctT2JqZWN0IFN5c3RlbS5UZXh0LlVURjhFbmNvZGluZygkZmFsc2UsICR0cnVlKQokVXRmOE5v
>>"%PATCH_B64%" echo(Qm9tID0gTmV3LU9iamVjdCBTeXN0ZW0uVGV4dC5VVEY4RW5jb2RpbmcoJGZhbHNlKQokQmFja3Vw
>>"%PATCH_B64%" echo(Um9vdCA9IEpvaW4tUGF0aCAkZW52OlRFTVAgKAogICAgJ1RyYWNlVHJhY2tDYXJfVElfQ0hBU1NJ
>>"%PATCH_B64%" echo(U19GSVhfVjNfJyArIChHZXQtRGF0ZSAtRm9ybWF0ICd5eXl5TU1kZF9ISG1tc3MnKQopCgokQ2hh
>>"%PATCH_B64%" echo(c3Npc1JlcGxhY2VtZW50QmFzZTY0ID0gJ2RtOXBaQ0JVWlhOMFgwTm9ZWE56YVhORGJXUmZURzlu
>>"%PATCH_B64%" echo(S0hadmFXUXBDbnNLSUNBZ0lFTm9ZWE56YVhOZlNXNW1iMTkwSUdsdVptODdDaUFnSUNCemRHRjBh
>>"%PATCH_B64%" echo(V01nWTJoaGNpQmlkV1piTWpVMlhUc0tJQ0FnSUhWcGJuUTRYM1FnYlc5MGIzSmZiV0Z6YXlBOUlE
>>"%PATCH_B64%" echo(QlZPd29nSUNBZ2RXbHVkRGhmZENCbGJtTnZaR1Z5WDIxaGMyc2dQU0F3VlRzS0lDQWdJR2x1ZENC
>>"%PATCH_B64%" echo(dU93b0tJQ0FnSUdsbUlDaERhR0Z6YzJselgwZGxkRWx1Wm04b0ptbHVabThwSUNFOUlFSlRVRjlQ
>>"%PATCH_B64%" echo(U3lrZ2V3b2dJQ0FnSUNBZ0lISmxkSFZ5YmpzS0lDQWdJSDBLQ2lBZ0lDQnBaaUFvVFc5MGIzSmZT
>>"%PATCH_B64%" echo(WE5GYm1GaWJHVmtLRTFQVkU5U1gwWk1LU0FoUFNBd1ZTa2diVzkwYjNKZmJXRnpheUI4UFNBd2VE
>>"%PATCH_B64%" echo(QXhWVHNLSUNBZ0lHbG1JQ2hOYjNSdmNsOUpjMFZ1WVdKc1pXUW9UVTlVVDFKZlJsSXBJQ0U5SURC
>>"%PATCH_B64%" echo(VktTQnRiM1J2Y2w5dFlYTnJJSHc5SURCNE1ESlZPd29nSUNBZ2FXWWdLRTF2ZEc5eVgwbHpSVzVo
>>"%PATCH_B64%" echo(WW14bFpDaE5UMVJQVWw5U1RDa2dJVDBnTUZVcElHMXZkRzl5WDIxaGMyc2dmRDBnTUhnd05GVTdD
>>"%PATCH_B64%" echo(aUFnSUNCcFppQW9UVzkwYjNKZlNYTkZibUZpYkdWa0tFMVBWRTlTWDFKU0tTQWhQU0F3VlNrZ2JX
>>"%PATCH_B64%" echo(OTBiM0pmYldGemF5QjhQU0F3ZURBNFZUc0tDaUFnSUNCcFppQW9SSEoyWDBWdVkyOWtaWEpmU1hO
>>"%PATCH_B64%" echo(WGFHVmxiRVZ1WVdKc1pXUW9WMGhGUlV4ZlJrd3BJQ0U5SURCVktTQmxibU52WkdWeVgyMWhjMnNn
>>"%PATCH_B64%" echo(ZkQwZ01IZ3dNVlU3Q2lBZ0lDQnBaaUFvUkhKMlgwVnVZMjlrWlhKZlNYTlhhR1ZsYkVWdVlXSnNa
>>"%PATCH_B64%" echo(V1FvVjBoRlJVeGZSbElwSUNFOUlEQlZLU0JsYm1OdlpHVnlYMjFoYzJzZ2ZEMGdNSGd3TWxVN0Np
>>"%PATCH_B64%" echo(QWdJQ0JwWmlBb1JISjJYMFZ1WTI5a1pYSmZTWE5YYUdWbGJFVnVZV0pzWldRb1YwaEZSVXhmVWt3
>>"%PATCH_B64%" echo(cElDRTlJREJWS1NCbGJtTnZaR1Z5WDIxaGMyc2dmRDBnTUhnd05GVTdDaUFnSUNCcFppQW9SSEoy
>>"%PATCH_B64%" echo(WDBWdVkyOWtaWEpmU1hOWGFHVmxiRVZ1WVdKc1pXUW9WMGhGUlV4ZlVsSXBJQ0U5SURCVktTQmxi
>>"%PATCH_B64%" echo(bU52WkdWeVgyMWhjMnNnZkQwZ01IZ3dPRlU3Q2dvZ0lDQWdiaUE5SUhOdWNISnBiblJtS0FvZ0lD
>>"%PATCH_B64%" echo(QWdJQ0FnSUdKMVppd0tJQ0FnSUNBZ0lDQnphWHBsYjJZb1luVm1LU3dLSUNBZ0lDQWdJQ0FpUTBo
>>"%PATCH_B64%" echo(VElHeHZiM0E5SlhVZ1ptRjFiSFE5SldRZ1ptRjFiSFJmYldGemF6MGxNREpZSUcxdmRHOXlQU1V3
>>"%PATCH_B64%" echo(TWxnZ1pXNWpQU1V3TWxnZ0lnb2dJQ0FnSUNBZ0lDSmhaMlU5Sld4MUlHOTNibVZ5UFNWa0lHMXZa
>>"%PATCH_B64%" echo(R1U5SldRZ1kyMWtQU1ZrTHlWa0lIUm5kRDBsWkM4bFpGeHlYRzRpTEFvZ0lDQWdJQ0FnSUNoMWJu
>>"%PATCH_B64%" echo(TnBaMjVsWkNCcGJuUXBhVzVtYnk1emNHVmxaRjlzYjI5d1gyVnVZV0pzWldRc0NpQWdJQ0FnSUNB
>>"%PATCH_B64%" echo(Z0tHbHVkQ2xwYm1adkxtWmhkV3gwTEFvZ0lDQWdJQ0FnSUNoMWJuTnBaMjVsWkNCcGJuUXBhVzVt
>>"%PATCH_B64%" echo(Ynk1bVlYVnNkRjkzYUdWbGJGOXRZWE5yTEFvZ0lDQWdJQ0FnSUNoMWJuTnBaMjVsWkNCcGJuUXBi
>>"%PATCH_B64%" echo(VzkwYjNKZmJXRnpheXdLSUNBZ0lDQWdJQ0FvZFc1emFXZHVaV1FnYVc1MEtXVnVZMjlrWlhKZmJX
>>"%PATCH_B64%" echo(RnpheXdLSUNBZ0lDQWdJQ0FvZFc1emFXZHVaV1FnYkc5dVp5bHBibVp2TG1OdmJXMWhibVJmWVdk
>>"%PATCH_B64%" echo(bFgyMXpMQW9nSUNBZ0lDQWdJQ2hwYm5RcGFXNW1ieTV2ZDI1bGNpd0tJQ0FnSUNBZ0lDQW9hVzUw
>>"%PATCH_B64%" echo(S1dsdVptOHViVzlrWlN3S0lDQWdJQ0FnSUNBb2FXNTBLV2x1Wm04dWJHVm1kRjkwWVhKblpYUmZZ
>>"%PATCH_B64%" echo(M0J6TEFvZ0lDQWdJQ0FnSUNocGJuUXBhVzVtYnk1eWFXZG9kRjkwWVhKblpYUmZZM0J6TEFvZ0lD
>>"%PATCH_B64%" echo(QWdJQ0FnSUNocGJuUXBhVzVtYnk1c1pXWjBYMkZ3Y0d4cFpXUmZkR0Z5WjJWMFgyTndjeXdLSUNB
>>"%PATCH_B64%" echo(Z0lDQWdJQ0FvYVc1MEtXbHVabTh1Y21sbmFIUmZZWEJ3YkdsbFpGOTBZWEpuWlhSZlkzQnpDaUFn
>>"%PATCH_B64%" echo(SUNBcE93b0tJQ0FnSUdsbUlDZ29iaUErSURBcElDWW1JQ2h1SUR3Z0tHbHVkQ2x6YVhwbGIyWW9Z
>>"%PATCH_B64%" echo(blZtS1NrcElIc0tJQ0FnSUNBZ0lDQW9kbTlwWkNsQ1UxQmZWVUZTVkY5WGNtbDBaVVp5WVcxbEtB
>>"%PATCH_B64%" echo(b2dJQ0FnSUNBZ0lDQWdJQ0JFUlVKVlIxOVZRVkpVWDFCUFVsUXNDaUFnSUNBZ0lDQWdJQ0FnSUNo
>>"%PATCH_B64%" echo(amIyNXpkQ0IxYVc1ME9GOTBJQ29wWW5WbUxBb2dJQ0FnSUNBZ0lDQWdJQ0FvZFdsdWRERTJYM1Fw
>>"%PATCH_B64%" echo(YmdvZ0lDQWdJQ0FnSUNrN0NpQWdJQ0I5Q2dvZ0lDQWdiaUE5SUhOdWNISnBiblJtS0FvZ0lDQWdJ
>>"%PATCH_B64%" echo(Q0FnSUdKMVppd0tJQ0FnSUNBZ0lDQnphWHBsYjJZb1luVm1LU3dLSUNBZ0lDQWdJQ0FpUTBoVElI
>>"%PATCH_B64%" echo(ZG9aV1ZzSUhKaGR6MGxiR1F2Sld4a0x5VnNaQzhsYkdRZ1ptSTlKV3hrTHlWc1pDOGxiR1F2Sld4
>>"%PATCH_B64%" echo(a0lDSUtJQ0FnSUNBZ0lDQWlabVk5SldRdkpXUXZKV1F2SldRZ2NHazlKV1F2SldRdkpXUXZKV1Fn
>>"%PATCH_B64%" echo(YjNWMFBTVmtMeVZrTHlWa0x5VmtYSEpjYmlJc0NpQWdJQ0FnSUNBZ0tHeHZibWNwUkhKMlgwVnVZ
>>"%PATCH_B64%" echo(MjlrWlhKZlIyVjBWMmhsWld4U1lYZFRjR1ZsWkVOd2N5aFhTRVZGVEY5R1RDa3NDaUFnSUNBZ0lD
>>"%PATCH_B64%" echo(QWdLR3h2Ym1jcFJISjJYMFZ1WTI5a1pYSmZSMlYwVjJobFpXeFNZWGRUY0dWbFpFTndjeWhYU0VW
>>"%PATCH_B64%" echo(RlRGOUdVaWtzQ2lBZ0lDQWdJQ0FnS0d4dmJtY3BSSEoyWDBWdVkyOWtaWEpmUjJWMFYyaGxaV3hT
>>"%PATCH_B64%" echo(WVhkVGNHVmxaRU53Y3loWFNFVkZURjlTVENrc0NpQWdJQ0FnSUNBZ0tHeHZibWNwUkhKMlgwVnVZ
>>"%PATCH_B64%" echo(MjlrWlhKZlIyVjBWMmhsWld4U1lYZFRjR1ZsWkVOd2N5aFhTRVZGVEY5U1Vpa3NDaUFnSUNBZ0lD
>>"%PATCH_B64%" echo(QWdLR3h2Ym1jcGFXNW1ieTVtYkY5bVpXVmtZbUZqYTE5amNITXNDaUFnSUNBZ0lDQWdLR3h2Ym1j
>>"%PATCH_B64%" echo(cGFXNW1ieTVtY2w5bVpXVmtZbUZqYTE5amNITXNDaUFnSUNBZ0lDQWdLR3h2Ym1jcGFXNW1ieTV5
>>"%PATCH_B64%" echo(YkY5bVpXVmtZbUZqYTE5amNITXNDaUFnSUNBZ0lDQWdLR3h2Ym1jcGFXNW1ieTV5Y2w5bVpXVmtZ
>>"%PATCH_B64%" echo(bUZqYTE5amNITXNDaUFnSUNBZ0lDQWdLR2x1ZENscGJtWnZMbVpzWDJabFpXUm1iM0ozWVhKa0xB
>>"%PATCH_B64%" echo(b2dJQ0FnSUNBZ0lDaHBiblFwYVc1bWJ5NW1jbDltWldWa1ptOXlkMkZ5WkN3S0lDQWdJQ0FnSUNB
>>"%PATCH_B64%" echo(b2FXNTBLV2x1Wm04dWNteGZabVZsWkdadmNuZGhjbVFzQ2lBZ0lDQWdJQ0FnS0dsdWRDbHBibVp2
>>"%PATCH_B64%" echo(TG5KeVgyWmxaV1JtYjNKM1lYSmtMQW9nSUNBZ0lDQWdJQ2hwYm5RcGFXNW1ieTVtYkY5d2FXUmZZ
>>"%PATCH_B64%" echo(Mjl5Y21WamRHbHZiaXdLSUNBZ0lDQWdJQ0FvYVc1MEtXbHVabTh1Wm5KZmNHbGtYMk52Y25KbFkz
>>"%PATCH_B64%" echo(UnBiMjRzQ2lBZ0lDQWdJQ0FnS0dsdWRDbHBibVp2TG5Kc1gzQnBaRjlqYjNKeVpXTjBhVzl1TEFv
>>"%PATCH_B64%" echo(Z0lDQWdJQ0FnSUNocGJuUXBhVzVtYnk1eWNsOXdhV1JmWTI5eWNtVmpkR2x2Yml3S0lDQWdJQ0Fn
>>"%PATCH_B64%" echo(SUNBb2FXNTBLV2x1Wm04dVpteGZiM1YwY0hWMExBb2dJQ0FnSUNBZ0lDaHBiblFwYVc1bWJ5NW1j
>>"%PATCH_B64%" echo(bDl2ZFhSd2RYUXNDaUFnSUNBZ0lDQWdLR2x1ZENscGJtWnZMbkpzWDI5MWRIQjFkQ3dLSUNBZ0lD
>>"%PATCH_B64%" echo(QWdJQ0FvYVc1MEtXbHVabTh1Y25KZmIzVjBjSFYwQ2lBZ0lDQXBPd29LSUNBZ0lHbG1JQ2dvYmlB
>>"%PATCH_B64%" echo(K0lEQXBJQ1ltSUNodUlEd2dLR2x1ZENsemFYcGxiMllvWW5WbUtTa3BJSHNLSUNBZ0lDQWdJQ0Fv
>>"%PATCH_B64%" echo(ZG05cFpDbENVMUJmVlVGU1ZGOVhjbWwwWlVaeVlXMWxLQW9nSUNBZ0lDQWdJQ0FnSUNCRVJVSlZS
>>"%PATCH_B64%" echo(MTlWUVZKVVgxQlBVbFFzQ2lBZ0lDQWdJQ0FnSUNBZ0lDaGpiMjV6ZENCMWFXNTBPRjkwSUNvcFlu
>>"%PATCH_B64%" echo(Vm1MQW9nSUNBZ0lDQWdJQ0FnSUNBb2RXbHVkREUyWDNRcGJnb2dJQ0FnSUNBZ0lDazdDaUFnSUNC
>>"%PATCH_B64%" echo(OUNuMD0nCiRVYXJ0UmVwbGFjZW1lbnRCYXNlNjQgPSAnYzNSaGRHbGpJSFp2YVdRZ1ZVRlNWRjlM
>>"%PATCH_B64%" echo(YVdOclZIZ29WVUZTVkY5UWIzSjBYM1FnY0c5eWRDa0tld29nSUNBZ1ZVRlNWRjlTZFc1MGFXMWxY
>>"%PATCH_B64%" echo(M1FnS25KME93b2dJQ0FnVlVGU1ZGOVNaV2R6SUNwcGJuTjBPd29nSUNBZ2RXbHVkRE15WDNRZ2NI
>>"%PATCH_B64%" echo(SnBiV0Z6YXpzS0NpQWdJQ0JwWmlBb2NHOXlkQ0ErUFNCVlFWSlVYMUJQVWxSZlEwOVZUbFFwSUhz
>>"%PATCH_B64%" echo(S0lDQWdJQ0FnSUNCeVpYUjFjbTQ3Q2lBZ0lDQjlDZ29nSUNBZ0x5b0tJQ0FnSUNBcUlPUzR1K1cr
>>"%PATCH_B64%" echo(cXVlT3IrT0FnZVdRanVXUHNPUzd1K1dLb2VXU2pGVkJVbFRsajVIcGdJSGt1SzNtbHEzcGc3M2xq
>>"%PATCH_B64%" echo(Ni9vZzczbWpxam92NXZsajVIcGdJSHBtSi9saUpmamdJSUtJQ0FnSUNBcUlPV3doblI0WDNSaGFX
>>"%PATCH_B64%" echo(emxrb3hVV09TNHJlYVdyZVc4Z09XRnMrYVV2dVdjcU9XUWpPUzRnT1M0dE9lVmpPV011dSs4ak9t
>>"%PATCH_B64%" echo(QnYrV0ZqZW1WdithWHBlVy9sK1dQa2VtQWdlYVh0Z29nSUNBZ0lDb2c1TGk3NWI2cTU0NnY1TGlP
>>"%PATCH_B64%" echo(NUxpdDVwYXQ1WkNNNXBlMjVMK3U1cFM1NlppZjVZaVg3N3lNNllDZzVvaVE1TG14NTZDQjVvaVc1
>>"%PATCH_B64%" echo(WStSNllDQjVZR2M1cTJpNDRDQ0NpQWdJQ0FnS2k4S0lDQWdJSEJ5YVcxaGMyc2dQU0JDVTFCZlJX
>>"%PATCH_B64%" echo(NTBaWEpEY21sMGFXTmhiQ2dwT3dvS0lDQWdJSEowSUQwZ0puTmZkV0Z5ZEY5eWRGdHdiM0owWFRz
>>"%PATCH_B64%" echo(S0lDQWdJR2x1YzNRZ1BTQnpYM1ZoY25SZlkyWm5XM0J2Y25SZExtbHVjM1E3Q2dvZ0lDQWdkMmhw
>>"%PATCH_B64%" echo(YkdVZ0tDaHlkQzArZEhoZmRHRnBiQ0FoUFNCeWRDMCtkSGhmYUdWaFpDa2dKaVlLSUNBZ0lDQWdJ
>>"%PATCH_B64%" echo(Q0FnSUNBaFJFeGZWVUZTVkY5TllXbHVYMmx6VkZoR1NVWlBSblZzYkNocGJuTjBLU2tnZXdvZ0lD
>>"%PATCH_B64%" echo(QWdJQ0FnSUVSTVgxVkJVbFJmVFdGcGJsOTBjbUZ1YzIxcGRFUmhkR0VvYVc1emRDd2djMTkxWVhK
>>"%PATCH_B64%" echo(MFgzUjRYM0pwYm1kYmNHOXlkRjFiY25RdFBuUjRYM1JoYVd4ZEtUc0tJQ0FnSUNBZ0lDQnlkQzAr
>>"%PATCH_B64%" echo(ZEhoZmRHRnBiQ0E5SUZWQlVsUmZUbVY0ZENoeWRDMCtkSGhmZEdGcGJDd2dWVUZTVkY5VVdGOUNW
>>"%PATCH_B64%" echo(VVpmVTBsYVJTazdDaUFnSUNCOUNnb2dJQ0FnYVdZZ0tISjBMVDUwZUY5MFlXbHNJRDA5SUhKMExU
>>"%PATCH_B64%" echo(NTBlRjlvWldGa0tTQjdDaUFnSUNBZ0lDQWdSRXhmVlVGU1ZGOU5ZV2x1WDJScGMyRmliR1ZKYm5S
>>"%PATCH_B64%" echo(bGNuSjFjSFFvYVc1emRDd2dSRXhmVlVGU1ZGOU5RVWxPWDBsT1ZFVlNVbFZRVkY5VVdDazdDaUFn
>>"%PATCH_B64%" echo(SUNCOUlHVnNjMlVnZXdvZ0lDQWdJQ0FnSUVSTVgxVkJVbFJmVFdGcGJsOWxibUZpYkdWSmJuUmxj
>>"%PATCH_B64%" echo(bkoxY0hRb2FXNXpkQ3dnUkV4ZlZVRlNWRjlOUVVsT1gwbE9WRVZTVWxWUVZGOVVXQ2s3Q2lBZ0lD
>>"%PATCH_B64%" echo(QjlDZ29nSUNBZ1FsTlFYMFY0YVhSRGNtbDBhV05oYkNod2NtbHRZWE5yS1RzS2ZRPT0nCgokU3Rh
>>"%PATCH_B64%" echo(cnR1cFBhdGggPSAna2VpbC9zdGFydHVwX21zcG0wZzM1MXhfdXZpc2lvbi5zJwokVGVzdFBhdGgg
>>"%PATCH_B64%" echo(PSAnVXNlci9UZXN0L3Rlc3QuYycKJFVhcnRQYXRoID0gJ1VzZXIvQlNQL2JzcF91YXJ0LmMnCgpm
>>"%PATCH_B64%" echo(dW5jdGlvbiBHZXQtUHJvamVjdEZpbGVQYXRoIHsKICAgIHBhcmFtKFtzdHJpbmddJFJlbGF0aXZl
>>"%PATCH_B64%" echo(UGF0aCkKCiAgICByZXR1cm4gSm9pbi1QYXRoICRQcm9qZWN0Um9vdCAoJFJlbGF0aXZlUGF0aCAt
>>"%PATCH_B64%" echo(cmVwbGFjZSAnLycsICdcJykKfQoKZnVuY3Rpb24gUmVhZC1Qcm9qZWN0VXRmOCB7CiAgICBwYXJh
>>"%PATCH_B64%" echo(bShbc3RyaW5nXSRSZWxhdGl2ZVBhdGgpCgogICAgJFBhdGggPSBHZXQtUHJvamVjdEZpbGVQYXRo
>>"%PATCH_B64%" echo(ICRSZWxhdGl2ZVBhdGgKICAgIGlmICgtbm90IChUZXN0LVBhdGggLUxpdGVyYWxQYXRoICRQYXRo
>>"%PATCH_B64%" echo(IC1QYXRoVHlwZSBMZWFmKSkgewogICAgICAgIHRocm93ICgn57y65bCR5bel56iL5paH5Lu277ya
>>"%PATCH_B64%" echo(JyArICRSZWxhdGl2ZVBhdGgpCiAgICB9CgogICAgcmV0dXJuIFtJTy5GaWxlXTo6UmVhZEFsbFRl
>>"%PATCH_B64%" echo(eHQoJFBhdGgsICRVdGY4U3RyaWN0KQp9CgpmdW5jdGlvbiBEZWNvZGUtVXRmOEJhc2U2NCB7CiAg
>>"%PATCH_B64%" echo(ICBwYXJhbShbc3RyaW5nXSRFbmNvZGVkVGV4dCkKCiAgICByZXR1cm4gW1RleHQuRW5jb2Rpbmdd
>>"%PATCH_B64%" echo(OjpVVEY4LkdldFN0cmluZygKICAgICAgICBbQ29udmVydF06OkZyb21CYXNlNjRTdHJpbmcoJEVu
>>"%PATCH_B64%" echo(Y29kZWRUZXh0KQogICAgKQp9CgpmdW5jdGlvbiBSZXBsYWNlLUNGdW5jdGlvbiB7CiAgICBwYXJh
>>"%PATCH_B64%" echo(bSgKICAgICAgICBbc3RyaW5nXSRUZXh0LAogICAgICAgIFtzdHJpbmddJFNpZ25hdHVyZSwKICAg
>>"%PATCH_B64%" echo(ICAgICBbc3RyaW5nXSRSZXBsYWNlbWVudAogICAgKQoKICAgICRTdGFydEluZGV4ID0gJFRleHQu
>>"%PATCH_B64%" echo(SW5kZXhPZigkU2lnbmF0dXJlKQogICAgaWYgKCRTdGFydEluZGV4IC1sdCAwKSB7CiAgICAgICAg
>>"%PATCH_B64%" echo(dGhyb3cgKCfmnKrmib7liLDlh73mlbDvvJonICsgJFNpZ25hdHVyZSkKICAgIH0KCiAgICAkQnJh
>>"%PATCH_B64%" echo(Y2VTdGFydCA9ICRUZXh0LkluZGV4T2YoJ3snLCAkU3RhcnRJbmRleCkKICAgIGlmICgkQnJhY2VT
>>"%PATCH_B64%" echo(dGFydCAtbHQgMCkgewogICAgICAgIHRocm93ICgn5Ye95pWw57y65bCR5bem6Iqx5ous5Y+377ya
>>"%PATCH_B64%" echo(JyArICRTaWduYXR1cmUpCiAgICB9CgogICAgJERlcHRoID0gMAogICAgJEluU3RyaW5nID0gJGZh
>>"%PATCH_B64%" echo(bHNlCiAgICAkSW5DaGFyID0gJGZhbHNlCiAgICAkSW5MaW5lQ29tbWVudCA9ICRmYWxzZQogICAg
>>"%PATCH_B64%" echo(JEluQmxvY2tDb21tZW50ID0gJGZhbHNlCiAgICAkRXNjYXBlZCA9ICRmYWxzZQogICAgJEVuZElu
>>"%PATCH_B64%" echo(ZGV4ID0gLTEKCiAgICBmb3IgKCRJbmRleCA9ICRCcmFjZVN0YXJ0OyAkSW5kZXggLWx0ICRUZXh0
>>"%PATCH_B64%" echo(Lkxlbmd0aDsgJEluZGV4KyspIHsKICAgICAgICAkQ3VycmVudCA9ICRUZXh0WyRJbmRleF0KICAg
>>"%PATCH_B64%" echo(ICAgICAkTmV4dCA9IGlmICgoJEluZGV4ICsgMSkgLWx0ICRUZXh0Lkxlbmd0aCkgewogICAgICAg
>>"%PATCH_B64%" echo(ICAgICAkVGV4dFskSW5kZXggKyAxXQogICAgICAgIH0gZWxzZSB7CiAgICAgICAgICAgIFtjaGFy
>>"%PATCH_B64%" echo(XTAKICAgICAgICB9CgogICAgICAgIGlmICgkSW5MaW5lQ29tbWVudCkgewogICAgICAgICAgICBp
>>"%PATCH_B64%" echo(ZiAoJEN1cnJlbnQgLWVxICJgbiIpIHsKICAgICAgICAgICAgICAgICRJbkxpbmVDb21tZW50ID0g
>>"%PATCH_B64%" echo(JGZhbHNlCiAgICAgICAgICAgIH0KICAgICAgICAgICAgY29udGludWUKICAgICAgICB9CgogICAg
>>"%PATCH_B64%" echo(ICAgIGlmICgkSW5CbG9ja0NvbW1lbnQpIHsKICAgICAgICAgICAgaWYgKCgkQ3VycmVudCAtZXEg
>>"%PATCH_B64%" echo(JyonKSAtYW5kICgkTmV4dCAtZXEgJy8nKSkgewogICAgICAgICAgICAgICAgJEluQmxvY2tDb21t
>>"%PATCH_B64%" echo(ZW50ID0gJGZhbHNlCiAgICAgICAgICAgICAgICAkSW5kZXgrKwogICAgICAgICAgICB9CiAgICAg
>>"%PATCH_B64%" echo(ICAgICAgIGNvbnRpbnVlCiAgICAgICAgfQoKICAgICAgICBpZiAoJEluU3RyaW5nKSB7CiAgICAg
>>"%PATCH_B64%" echo(ICAgICAgIGlmICgkRXNjYXBlZCkgewogICAgICAgICAgICAgICAgJEVzY2FwZWQgPSAkZmFsc2UK
>>"%PATCH_B64%" echo(ICAgICAgICAgICAgfSBlbHNlaWYgKCRDdXJyZW50IC1lcSAnXCcpIHsKICAgICAgICAgICAgICAg
>>"%PATCH_B64%" echo(ICRFc2NhcGVkID0gJHRydWUKICAgICAgICAgICAgfSBlbHNlaWYgKCRDdXJyZW50IC1lcSAnIicp
>>"%PATCH_B64%" echo(IHsKICAgICAgICAgICAgICAgICRJblN0cmluZyA9ICRmYWxzZQogICAgICAgICAgICB9CiAgICAg
>>"%PATCH_B64%" echo(ICAgICAgIGNvbnRpbnVlCiAgICAgICAgfQoKICAgICAgICBpZiAoJEluQ2hhcikgewogICAgICAg
>>"%PATCH_B64%" echo(ICAgICBpZiAoJEVzY2FwZWQpIHsKICAgICAgICAgICAgICAgICRFc2NhcGVkID0gJGZhbHNlCiAg
>>"%PATCH_B64%" echo(ICAgICAgICAgIH0gZWxzZWlmICgkQ3VycmVudCAtZXEgJ1wnKSB7CiAgICAgICAgICAgICAgICAk
>>"%PATCH_B64%" echo(RXNjYXBlZCA9ICR0cnVlCiAgICAgICAgICAgIH0gZWxzZWlmICgkQ3VycmVudCAtZXEgIiciKSB7
>>"%PATCH_B64%" echo(CiAgICAgICAgICAgICAgICAkSW5DaGFyID0gJGZhbHNlCiAgICAgICAgICAgIH0KICAgICAgICAg
>>"%PATCH_B64%" echo(ICAgY29udGludWUKICAgICAgICB9CgogICAgICAgIGlmICgoJEN1cnJlbnQgLWVxICcvJykgLWFu
>>"%PATCH_B64%" echo(ZCAoJE5leHQgLWVxICcvJykpIHsKICAgICAgICAgICAgJEluTGluZUNvbW1lbnQgPSAkdHJ1ZQog
>>"%PATCH_B64%" echo(ICAgICAgICAgICAkSW5kZXgrKwogICAgICAgICAgICBjb250aW51ZQogICAgICAgIH0KCiAgICAg
>>"%PATCH_B64%" echo(ICAgaWYgKCgkQ3VycmVudCAtZXEgJy8nKSAtYW5kICgkTmV4dCAtZXEgJyonKSkgewogICAgICAg
>>"%PATCH_B64%" echo(ICAgICAkSW5CbG9ja0NvbW1lbnQgPSAkdHJ1ZQogICAgICAgICAgICAkSW5kZXgrKwogICAgICAg
>>"%PATCH_B64%" echo(ICAgICBjb250aW51ZQogICAgICAgIH0KCiAgICAgICAgaWYgKCRDdXJyZW50IC1lcSAnIicpIHsK
>>"%PATCH_B64%" echo(ICAgICAgICAgICAgJEluU3RyaW5nID0gJHRydWUKICAgICAgICAgICAgY29udGludWUKICAgICAg
>>"%PATCH_B64%" echo(ICB9CgogICAgICAgIGlmICgkQ3VycmVudCAtZXEgIiciKSB7CiAgICAgICAgICAgICRJbkNoYXIg
>>"%PATCH_B64%" echo(PSAkdHJ1ZQogICAgICAgICAgICBjb250aW51ZQogICAgICAgIH0KCiAgICAgICAgaWYgKCRDdXJy
>>"%PATCH_B64%" echo(ZW50IC1lcSAneycpIHsKICAgICAgICAgICAgJERlcHRoKysKICAgICAgICB9IGVsc2VpZiAoJEN1
>>"%PATCH_B64%" echo(cnJlbnQgLWVxICd9JykgewogICAgICAgICAgICAkRGVwdGgtLQoKICAgICAgICAgICAgaWYgKCRE
>>"%PATCH_B64%" echo(ZXB0aCAtZXEgMCkgewogICAgICAgICAgICAgICAgJEVuZEluZGV4ID0gJEluZGV4ICsgMQogICAg
>>"%PATCH_B64%" echo(ICAgICAgICAgICAgYnJlYWsKICAgICAgICAgICAgfQogICAgICAgIH0KICAgIH0KCiAgICBpZiAo
>>"%PATCH_B64%" echo(JEVuZEluZGV4IC1sdCAwKSB7CiAgICAgICAgdGhyb3cgKCfml6Dms5Xnoa7lrprlh73mlbDnu5Pm
>>"%PATCH_B64%" echo(nZ/kvY3nva7vvJonICsgJFNpZ25hdHVyZSkKICAgIH0KCiAgICByZXR1cm4gKAogICAgICAgICRU
>>"%PATCH_B64%" echo(ZXh0LlN1YnN0cmluZygwLCAkU3RhcnRJbmRleCkgKwogICAgICAgICRSZXBsYWNlbWVudC5Ucmlt
>>"%PATCH_B64%" echo(RW5kKCkgKwogICAgICAgICRUZXh0LlN1YnN0cmluZygkRW5kSW5kZXgpCiAgICApCn0KCmZ1bmN0
>>"%PATCH_B64%" echo(aW9uIEJhY2t1cC1Qcm9qZWN0RmlsZSB7CiAgICBwYXJhbShbc3RyaW5nXSRSZWxhdGl2ZVBhdGgp
>>"%PATCH_B64%" echo(CgogICAgJFNvdXJjZVBhdGggPSBHZXQtUHJvamVjdEZpbGVQYXRoICRSZWxhdGl2ZVBhdGgKICAg
>>"%PATCH_B64%" echo(ICRCYWNrdXBQYXRoID0gSm9pbi1QYXRoICRCYWNrdXBSb290ICgkUmVsYXRpdmVQYXRoIC1yZXBs
>>"%PATCH_B64%" echo(YWNlICcvJywgJ1wnKQogICAgJEJhY2t1cFBhcmVudCA9IFNwbGl0LVBhdGggLVBhcmVudCAkQmFj
>>"%PATCH_B64%" echo(a3VwUGF0aAoKICAgIE5ldy1JdGVtIC1JdGVtVHlwZSBEaXJlY3RvcnkgLUZvcmNlIC1QYXRoICRC
>>"%PATCH_B64%" echo(YWNrdXBQYXJlbnQgfCBPdXQtTnVsbAogICAgQ29weS1JdGVtIC1MaXRlcmFsUGF0aCAkU291cmNl
>>"%PATCH_B64%" echo(UGF0aCAtRGVzdGluYXRpb24gJEJhY2t1cFBhdGggLUZvcmNlCn0KCmZ1bmN0aW9uIFJlc3RvcmUt
>>"%PATCH_B64%" echo(UHJvamVjdEZpbGVzIHsKICAgIGlmICgtbm90IChUZXN0LVBhdGggLUxpdGVyYWxQYXRoICRCYWNr
>>"%PATCH_B64%" echo(dXBSb290IC1QYXRoVHlwZSBDb250YWluZXIpKSB7CiAgICAgICAgcmV0dXJuCiAgICB9CgogICAg
>>"%PATCH_B64%" echo(Zm9yZWFjaCAoJFJlbGF0aXZlUGF0aCBpbiBAKCRTdGFydHVwUGF0aCwgJFRlc3RQYXRoLCAkVWFy
>>"%PATCH_B64%" echo(dFBhdGgpKSB7CiAgICAgICAgJEJhY2t1cFBhdGggPSBKb2luLVBhdGggJEJhY2t1cFJvb3QgKCRS
>>"%PATCH_B64%" echo(ZWxhdGl2ZVBhdGggLXJlcGxhY2UgJy8nLCAnXCcpCiAgICAgICAgaWYgKFRlc3QtUGF0aCAtTGl0
>>"%PATCH_B64%" echo(ZXJhbFBhdGggJEJhY2t1cFBhdGggLVBhdGhUeXBlIExlYWYpIHsKICAgICAgICAgICAgQ29weS1J
>>"%PATCH_B64%" echo(dGVtIC1MaXRlcmFsUGF0aCAkQmFja3VwUGF0aCBgCiAgICAgICAgICAgICAgICAtRGVzdGluYXRp
>>"%PATCH_B64%" echo(b24gKEdldC1Qcm9qZWN0RmlsZVBhdGggJFJlbGF0aXZlUGF0aCkgLUZvcmNlCiAgICAgICAgfQog
>>"%PATCH_B64%" echo(ICAgfQp9CgpmdW5jdGlvbiBXcml0ZS1Qcm9qZWN0VXRmOFByZXNlcnZlRW9sIHsKICAgIHBhcmFt
>>"%PATCH_B64%" echo(KAogICAgICAgIFtzdHJpbmddJFJlbGF0aXZlUGF0aCwKICAgICAgICBbc3RyaW5nXSRPcmlnaW5h
>>"%PATCH_B64%" echo(bFRleHQsCiAgICAgICAgW3N0cmluZ10kVXBkYXRlZFRleHQKICAgICkKCiAgICAkUGF0aCA9IEdl
>>"%PATCH_B64%" echo(dC1Qcm9qZWN0RmlsZVBhdGggJFJlbGF0aXZlUGF0aAogICAgJE5vcm1hbGl6ZWQgPSAoKCRVcGRh
>>"%PATCH_B64%" echo(dGVkVGV4dCAtcmVwbGFjZSAiYHJgbiIsICJgbiIpIC1yZXBsYWNlICJgciIsICJgbiIpCgogICAg
>>"%PATCH_B64%" echo(aWYgKCRPcmlnaW5hbFRleHQuQ29udGFpbnMoImByYG4iKSkgewogICAgICAgICROb3JtYWxpemVk
>>"%PATCH_B64%" echo(ID0gJE5vcm1hbGl6ZWQgLXJlcGxhY2UgImBuIiwgImByYG4iCiAgICB9CgogICAgW0lPLkZpbGVd
>>"%PATCH_B64%" echo(OjpXcml0ZUFsbFRleHQoJFBhdGgsICROb3JtYWxpemVkLCAkVXRmOE5vQm9tKQp9CgppZiAoR2V0
>>"%PATCH_B64%" echo(LUNvbW1hbmQgZ2l0IC1FcnJvckFjdGlvbiBTaWxlbnRseUNvbnRpbnVlKSB7CiAgICAkQ3VycmVu
>>"%PATCH_B64%" echo(dEhlYWQgPSAoJiBnaXQgcmV2LXBhcnNlIEhFQUQgMj4kbnVsbCkKCiAgICBpZiAoJExBU1RFWElU
>>"%PATCH_B64%" echo(Q09ERSAtZXEgMCkgewogICAgICAgIFdyaXRlLUhvc3QgKCflvZPliY1HaXQgSEVBRO+8micgKyAk
>>"%PATCH_B64%" echo(Q3VycmVudEhlYWQpCgogICAgICAgIGlmICgkQ3VycmVudEhlYWQgLW5lICRFeHBlY3RlZEhlYWQp
>>"%PATCH_B64%" echo(IHsKICAgICAgICAgICAgV3JpdGUtSG9zdCAoCiAgICAgICAgICAgICAgICAn5o+Q56S677ya5b2T
>>"%PATCH_B64%" echo(5YmNSEVBROS4jeaYr+iEmuacrOaguOWvueeJiOacrCAnICsKICAgICAgICAgICAgICAgICRFeHBl
>>"%PATCH_B64%" echo(Y3RlZEhlYWQgKwogICAgICAgICAgICAgICAgJ++8jOS7jeS8muaMieWHveaVsOe7k+aehOS/ruaU
>>"%PATCH_B64%" echo(ueOAgicKICAgICAgICAgICAgKQogICAgICAgIH0KICAgIH0KfQoKJFN0YXJ0dXBPcmlnaW5hbCA9
>>"%PATCH_B64%" echo(IFJlYWQtUHJvamVjdFV0ZjggJFN0YXJ0dXBQYXRoCiRUZXN0T3JpZ2luYWwgPSBSZWFkLVByb2pl
>>"%PATCH_B64%" echo(Y3RVdGY4ICRUZXN0UGF0aAokVWFydE9yaWdpbmFsID0gUmVhZC1Qcm9qZWN0VXRmOCAkVWFydFBh
>>"%PATCH_B64%" echo(dGgKCiRTdGFja1BhdHRlcm4gPSAnKD9tKV5TdGFja19TaXplXHMrRVFVXHMrMHhbMC05QS1GYS1m
>>"%PATCH_B64%" echo(XStccyokJwokU3RhY2tNYXRjaCA9IFtUZXh0LlJlZ3VsYXJFeHByZXNzaW9ucy5SZWdleF06Ok1h
>>"%PATCH_B64%" echo(dGNoKAogICAgJFN0YXJ0dXBPcmlnaW5hbCwKICAgICRTdGFja1BhdHRlcm4KKQoKaWYgKC1ub3Qg
>>"%PATCH_B64%" echo(JFN0YWNrTWF0Y2guU3VjY2VzcykgewogICAgdGhyb3cgJ+WQr+WKqOaWh+S7tuS4reacquaJvuWI
>>"%PATCH_B64%" echo(sFN0YWNrX1NpemXphY3nva7jgIInCn0KCiRTdGFja0hleE1hdGNoID0gW1RleHQuUmVndWxhckV4
>>"%PATCH_B64%" echo(cHJlc3Npb25zLlJlZ2V4XTo6TWF0Y2goCiAgICAkU3RhY2tNYXRjaC5WYWx1ZSwKICAgICcweFsw
>>"%PATCH_B64%" echo(LTlBLUZhLWZdKycKKQoKaWYgKC1ub3QgJFN0YWNrSGV4TWF0Y2guU3VjY2VzcykgewogICAgdGhy
>>"%PATCH_B64%" echo(b3cgJ+aXoOazleivu+WPluW9k+WJjVN0YWNrX1NpemXmlbDlgLzjgIInCn0KCiRDdXJyZW50U3Rh
>>"%PATCH_B64%" echo(Y2tTaXplID0gW0NvbnZlcnRdOjpUb1VJbnQzMigKICAgICRTdGFja0hleE1hdGNoLlZhbHVlLlN1
>>"%PATCH_B64%" echo(YnN0cmluZygyKSwKICAgIDE2CikKCmlmICgkQ3VycmVudFN0YWNrU2l6ZSAtbHQgNDA5Nikgewog
>>"%PATCH_B64%" echo(ICAgJFN0YXJ0dXBVcGRhdGVkID0gW1RleHQuUmVndWxhckV4cHJlc3Npb25zLlJlZ2V4XTo6UmVw
>>"%PATCH_B64%" echo(bGFjZSgKICAgICAgICAkU3RhcnR1cE9yaWdpbmFsLAogICAgICAgICRTdGFja1BhdHRlcm4sCiAg
>>"%PATCH_B64%" echo(ICAgICAgJ1N0YWNrX1NpemUgICAgICBFUVUgICAgIDB4MDAwMDEwMDAnLAogICAgICAgIDEKICAg
>>"%PATCH_B64%" echo(ICkKfSBlbHNlIHsKICAgICRTdGFydHVwVXBkYXRlZCA9ICRTdGFydHVwT3JpZ2luYWwKICAgIFdy
>>"%PATCH_B64%" echo(aXRlLUhvc3QgKCflvZPliY3kuLvmoIjlt7Lnu4/kuI3lsI/kuo40MDk25a2X6IqC77yaJyArICRD
>>"%PATCH_B64%" echo(dXJyZW50U3RhY2tTaXplKQp9CgokVGVzdFVwZGF0ZWQgPSBSZXBsYWNlLUNGdW5jdGlvbiBgCiAg
>>"%PATCH_B64%" echo(ICAkVGVzdE9yaWdpbmFsIGAKICAgICd2b2lkIFRlc3RfQ2hhc3Npc0NtZF9Mb2codm9pZCknIGAK
>>"%PATCH_B64%" echo(ICAgIChEZWNvZGUtVXRmOEJhc2U2NCAkQ2hhc3Npc1JlcGxhY2VtZW50QmFzZTY0KQoKJFVhcnRV
>>"%PATCH_B64%" echo(cGRhdGVkID0gUmVwbGFjZS1DRnVuY3Rpb24gYAogICAgJFVhcnRPcmlnaW5hbCBgCiAgICAnc3Rh
>>"%PATCH_B64%" echo(dGljIHZvaWQgVUFSVF9LaWNrVHgoVUFSVF9Qb3J0X3QgcG9ydCknIGAKICAgIChEZWNvZGUtVXRm
>>"%PATCH_B64%" echo(OEJhc2U2NCAkVWFydFJlcGxhY2VtZW50QmFzZTY0KQoKZm9yZWFjaCAoJFRva2VuIGluIEAoCiAg
>>"%PATCH_B64%" echo(ICAnc3RhdGljIGNoYXIgYnVmWzI1Nl07JywKICAgICdmYXVsdF9tYXNrPSUwMlggbW90b3I9JTAy
>>"%PATCH_B64%" echo(WCBlbmM9JTAyWCcsCiAgICAnQ0hTIHdoZWVsIHJhdz0nLAogICAgJ01vdG9yX0lzRW5hYmxlZChN
>>"%PATCH_B64%" echo(T1RPUl9GTCknLAogICAgJ0Rydl9FbmNvZGVyX0lzV2hlZWxFbmFibGVkKFdIRUVMX0ZMKScKKSkg
>>"%PATCH_B64%" echo(ewogICAgaWYgKC1ub3QgJFRlc3RVcGRhdGVkLkNvbnRhaW5zKCRUb2tlbikpIHsKICAgICAgICB0
>>"%PATCH_B64%" echo(aHJvdyAoJ3Rlc3QuY+S/ruaUuee7k+aenOe8uuWwke+8micgKyAkVG9rZW4pCiAgICB9Cn0KCmlm
>>"%PATCH_B64%" echo(ICgkVGVzdFVwZGF0ZWQuQ29udGFpbnMoJ2NoYXIgYnVmWzQwMF07JykpIHsKICAgIHRocm93ICd0
>>"%PATCH_B64%" echo(ZXN0LmPku43kv53nlZk0MDDlrZfoioLlsYDpg6jml6Xlv5fnvJPlhrLljLrjgIInCn0KCmZvcmVh
>>"%PATCH_B64%" echo(Y2ggKCRUb2tlbiBpbiBAKAogICAgJ3ByaW1hc2sgPSBCU1BfRW50ZXJDcml0aWNhbCgpOycsCiAg
>>"%PATCH_B64%" echo(ICAnQlNQX0V4aXRDcml0aWNhbChwcmltYXNrKTsnLAogICAgJ+S4u+W+queOr+OAgeWQjuWPsOS7
>>"%PATCH_B64%" echo(u+WKoeWSjFVBUlTlj5HpgIHkuK3mlq0nCikpIHsKICAgIGlmICgtbm90ICRVYXJ0VXBkYXRlZC5D
>>"%PATCH_B64%" echo(b250YWlucygkVG9rZW4pKSB7CiAgICAgICAgdGhyb3cgKCdic3BfdWFydC5j5L+u5pS557uT5p6c
>>"%PATCH_B64%" echo(57y65bCR77yaJyArICRUb2tlbikKICAgIH0KfQoKTmV3LUl0ZW0gLUl0ZW1UeXBlIERpcmVjdG9y
>>"%PATCH_B64%" echo(eSAtRm9yY2UgLVBhdGggJEJhY2t1cFJvb3QgfCBPdXQtTnVsbApCYWNrdXAtUHJvamVjdEZpbGUg
>>"%PATCH_B64%" echo(JFN0YXJ0dXBQYXRoCkJhY2t1cC1Qcm9qZWN0RmlsZSAkVGVzdFBhdGgKQmFja3VwLVByb2plY3RG
>>"%PATCH_B64%" echo(aWxlICRVYXJ0UGF0aApXcml0ZS1Ib3N0ICgn5aSH5Lu955uu5b2V77yaJyArICRCYWNrdXBSb290
>>"%PATCH_B64%" echo(KQoKdHJ5IHsKICAgIFdyaXRlLVByb2plY3RVdGY4UHJlc2VydmVFb2wgYAogICAgICAgICRTdGFy
>>"%PATCH_B64%" echo(dHVwUGF0aCBgCiAgICAgICAgJFN0YXJ0dXBPcmlnaW5hbCBgCiAgICAgICAgJFN0YXJ0dXBVcGRh
>>"%PATCH_B64%" echo(dGVkCgogICAgV3JpdGUtUHJvamVjdFV0ZjhQcmVzZXJ2ZUVvbCBgCiAgICAgICAgJFRlc3RQYXRo
>>"%PATCH_B64%" echo(IGAKICAgICAgICAkVGVzdE9yaWdpbmFsIGAKICAgICAgICAkVGVzdFVwZGF0ZWQKCiAgICBXcml0
>>"%PATCH_B64%" echo(ZS1Qcm9qZWN0VXRmOFByZXNlcnZlRW9sIGAKICAgICAgICAkVWFydFBhdGggYAogICAgICAgICRV
>>"%PATCH_B64%" echo(YXJ0T3JpZ2luYWwgYAogICAgICAgICRVYXJ0VXBkYXRlZAoKICAgICRTdGFydHVwRmluYWwgPSBS
>>"%PATCH_B64%" echo(ZWFkLVByb2plY3RVdGY4ICRTdGFydHVwUGF0aAogICAgJFRlc3RGaW5hbCA9IFJlYWQtUHJvamVj
>>"%PATCH_B64%" echo(dFV0ZjggJFRlc3RQYXRoCiAgICAkVWFydEZpbmFsID0gUmVhZC1Qcm9qZWN0VXRmOCAkVWFydFBh
>>"%PATCH_B64%" echo(dGgKCiAgICAkRmluYWxTdGFja01hdGNoID0gW1RleHQuUmVndWxhckV4cHJlc3Npb25zLlJlZ2V4
>>"%PATCH_B64%" echo(XTo6TWF0Y2goCiAgICAgICAgJFN0YXJ0dXBGaW5hbCwKICAgICAgICAkU3RhY2tQYXR0ZXJuCiAg
>>"%PATCH_B64%" echo(ICApCiAgICAkRmluYWxTdGFja0hleCA9IFtUZXh0LlJlZ3VsYXJFeHByZXNzaW9ucy5SZWdleF06
>>"%PATCH_B64%" echo(Ok1hdGNoKAogICAgICAgICRGaW5hbFN0YWNrTWF0Y2guVmFsdWUsCiAgICAgICAgJzB4WzAtOUEt
>>"%PATCH_B64%" echo(RmEtZl0rJwogICAgKQogICAgJEZpbmFsU3RhY2tTaXplID0gW0NvbnZlcnRdOjpUb1VJbnQzMigK
>>"%PATCH_B64%" echo(ICAgICAgICAkRmluYWxTdGFja0hleC5WYWx1ZS5TdWJzdHJpbmcoMiksCiAgICAgICAgMTYKICAg
>>"%PATCH_B64%" echo(ICkKCiAgICBpZiAoJEZpbmFsU3RhY2tTaXplIC1sdCA0MDk2KSB7CiAgICAgICAgdGhyb3cgJ+WG
>>"%PATCH_B64%" echo(meWFpeWQjuS4u+agiOS7jeWwj+S6jjQwOTblrZfoioLjgIInCiAgICB9CgogICAgaWYgKCRUZXN0
>>"%PATCH_B64%" echo(RmluYWwuQ29udGFpbnMoJ2NoYXIgYnVmWzQwMF07JykpIHsKICAgICAgICB0aHJvdyAn5YaZ5YWl
>>"%PATCH_B64%" echo(5ZCO5LuN5a2Y5ZyoNDAw5a2X6IqC5bGA6YOo5pel5b+X57yT5Yay5Yy644CCJwogICAgfQoKICAg
>>"%PATCH_B64%" echo(IGlmICgtbm90ICRVYXJ0RmluYWwuQ29udGFpbnMoCiAgICAgICAgJ3ByaW1hc2sgPSBCU1BfRW50
>>"%PATCH_B64%" echo(ZXJDcml0aWNhbCgpOycKICAgICkpIHsKICAgICAgICB0aHJvdyAn5YaZ5YWl5ZCOVUFSVOWPkemA
>>"%PATCH_B64%" echo(geS/neaKpOagoemqjOWksei0peOAgicKICAgIH0KCiAgICBpZiAoR2V0LUNvbW1hbmQgZ2l0IC1F
>>"%PATCH_B64%" echo(cnJvckFjdGlvbiBTaWxlbnRseUNvbnRpbnVlKSB7CiAgICAgICAgV3JpdGUtSG9zdCAnJwogICAg
>>"%PATCH_B64%" echo(ICAgIFdyaXRlLUhvc3QgJ0dpdOW3ruW8guajgOafpe+8micKCiAgICAgICAgJiBnaXQgZGlmZiAt
>>"%PATCH_B64%" echo(LWNoZWNrIC0tIGAKICAgICAgICAgICAgJFN0YXJ0dXBQYXRoIGAKICAgICAgICAgICAgJFRlc3RQ
>>"%PATCH_B64%" echo(YXRoIGAKICAgICAgICAgICAgJFVhcnRQYXRoCgogICAgICAgIGlmICgkTEFTVEVYSVRDT0RFIC1u
>>"%PATCH_B64%" echo(ZSAwKSB7CiAgICAgICAgICAgIHRocm93ICfkuInkuKrnm67moIfmlofku7bnmoRnaXQgZGlmZiAt
>>"%PATCH_B64%" echo(LWNoZWNr5Y+R546w5qC85byP6Zeu6aKY44CCJwogICAgICAgIH0KICAgIH0KCiAgICBXcml0ZS1I
>>"%PATCH_B64%" echo(b3N0ICcnCiAgICBXcml0ZS1Ib3N0ICflt7LlrozmiJDvvJonCiAgICBXcml0ZS1Ib3N0ICgnICDk
>>"%PATCH_B64%" echo(uLvmoIjlpKflsI/vvJonICsgJEZpbmFsU3RhY2tTaXplICsgJyDlrZfoioInKQogICAgV3JpdGUt
>>"%PATCH_B64%" echo(SG9zdCAnICBDaGFzc2lz5pel5b+X57yT5Yay5Yy65pS55Li66Z2Z5oCBMjU25a2X6IqC5bm25ouG
>>"%PATCH_B64%" echo(5oiQ5Lik6KGMJwogICAgV3JpdGUtSG9zdCAnICBVQVJUIFRY6Zif5YiX5o6o6L+b5Yqg5YWl5Li0
>>"%PATCH_B64%" echo(55WM5Yy65L+d5oqkJwogICAgV3JpdGUtSG9zdCAnICDmnKrkv67mlLnku7vkvZVNYXJrZG93buaW
>>"%PATCH_B64%" echo(h+ahoycKICAgIFdyaXRlLUhvc3QgJycKICAgIFdyaXRlLUhvc3QgJ+ivt+aJp+ihjFJlYnVpbGQg
>>"%PATCH_B64%" echo(YWxsIHRhcmdldCBmaWxlc+W5tumHjeaWsOeDp+W9leOAgicKfSBjYXRjaCB7CiAgICBXcml0ZS1I
>>"%PATCH_B64%" echo(b3N0ICgn5Y+R55Sf6ZSZ6K+v77yM5q2j5Zyo5oGi5aSN5aSH5Lu977yaJyArICRfLkV4Y2VwdGlv
>>"%PATCH_B64%" echo(bi5NZXNzYWdlKQogICAgUmVzdG9yZS1Qcm9qZWN0RmlsZXMKICAgIHRocm93Cn0K

powershell.exe -NoProfile -ExecutionPolicy Bypass -Command ^
  "$b=[IO.File]::ReadAllText($env:PATCH_B64); $b=[Text.RegularExpressions.Regex]::Replace($b,'\s',''); [IO.File]::WriteAllBytes($env:PATCH_PS1,[Convert]::FromBase64String($b))"

if errorlevel 1 (
    echo.
    echo [FAILED] Cannot decode PowerShell script.
    echo Base64 file: %PATCH_B64%
    popd
    pause
    exit /b 1
)

powershell.exe -NoProfile -ExecutionPolicy Bypass -File "%PATCH_PS1%" >"%PATCH_LOG%" 2>&1
set "RC=%ERRORLEVEL%"
type "%PATCH_LOG%"

if "%RC%"=="0" (
    del /q "%PATCH_B64%" "%PATCH_PS1%" "%PATCH_LOG%" >nul 2>nul
    echo.
    echo [OK] TI chassis stack and UART fix v3 completed successfully.
    popd
    pause
    exit /b 0
)

echo.
echo [FAILED] Error code: %RC%
echo Log: %PATCH_LOG%
echo Base64 file: %PATCH_B64%
echo PowerShell file: %PATCH_PS1%
echo The three target files were restored from backup when writing had started.
popd
pause
exit /b %RC%
